// This file is @generated by prost-build.
/// ===========================================
/// OVERRIDE FIELD TYPE (permissions)
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OverrideField {
    /// Allowed permissions
    #[prost(int64, tag = "1")]
    pub allow: i64,
    /// Denied permissions
    #[prost(int64, tag = "2")]
    pub deny: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Role {
    /// Role name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Permissions available to this role
    #[prost(message, optional, tag = "2")]
    pub permissions: ::core::option::Option<OverrideField>,
    /// Colour used for this role (any valid CSS colour, optional)
    #[prost(string, optional, tag = "3")]
    pub colour: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether this role should be shown separately on the member sidebar
    #[prost(bool, tag = "4")]
    pub hoist: bool,
    /// Ranking of this role
    #[prost(int64, tag = "5")]
    pub rank: i64,
}
/// Group channel type
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelGroup {
    /// User id of the owner of the group
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// Display name of the channel
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Channel description
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Array of user ids participating in channel
    #[prost(string, repeated, tag = "4")]
    pub recipients: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Custom icon attachment
    #[prost(message, optional, tag = "5")]
    pub icon: ::core::option::Option<super::super::shared::v1::File>,
    /// Id of the last message sent in this channel
    #[prost(string, optional, tag = "6")]
    pub last_message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Permissions assigned to members of this group (does not apply to owner)
    #[prost(int64, optional, tag = "7")]
    pub permissions: ::core::option::Option<i64>,
    /// Whether this group is marked as not safe for work
    #[prost(bool, tag = "8")]
    pub nsfw: bool,
}
/// Saved messages channel type
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelSavedMessages {
    /// Id of the user this channel belongs to
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// Text channel type
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelText {
    /// Id of the server this channel belongs to
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// Display name of the channel
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Channel description (optional)
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Custom icon attachment (optional)
    #[prost(message, optional, tag = "4")]
    pub icon: ::core::option::Option<super::super::shared::v1::File>,
    /// Id of the last message sent in this channel (optional)
    #[prost(string, optional, tag = "5")]
    pub last_message_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Default permissions assigned to users in this channel (optional)
    #[prost(message, optional, tag = "6")]
    pub default_permissions: ::core::option::Option<OverrideField>,
    /// Map of role_id -> permissions
    #[prost(map = "string, message", tag = "7")]
    pub role_permissions: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        OverrideField,
    >,
    /// Whether this channel is marked as not safe for work
    #[prost(bool, tag = "8")]
    pub nsfw: bool,
}
/// Direct message channel type
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelDirectMessage {
    /// Whether this direct message channel is currently open on both sides
    #[prost(bool, tag = "1")]
    pub active: bool,
    /// 2-tuple of user ids participating in direct message
    #[prost(string, repeated, tag = "2")]
    pub recipients: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Id of the last message sent in this channel
    #[prost(string, optional, tag = "3")]
    pub last_message_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// ===========================================
/// MAIN CHANNELS TABLE
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Channel {
    /// ULID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 'saved_messages', 'direct_message', 'group', 'text_channel'
    #[prost(string, tag = "2")]
    pub channel_type: ::prost::alloc::string::String,
    /// Maximum users allowed in voice channel
    #[prost(int32, optional, tag = "7")]
    pub voice_max_users: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<super::super::shared::v1::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub updated_at: ::core::option::Option<super::super::shared::v1::Timestamp>,
    /// Channel types (oneof - only one is set based on channel_type)
    #[prost(oneof = "channel::ChannelData", tags = "3, 4, 5, 6")]
    pub channel_data: ::core::option::Option<channel::ChannelData>,
}
/// Nested message and enum types in `Channel`.
pub mod channel {
    /// Channel types (oneof - only one is set based on channel_type)
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ChannelData {
        #[prost(message, tag = "3")]
        Saved(super::ChannelSavedMessages),
        #[prost(message, tag = "4")]
        Direct(super::ChannelDirectMessage),
        #[prost(message, tag = "5")]
        Group(super::ChannelGroup),
        #[prost(message, tag = "6")]
        Text(super::ChannelText),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsCreateRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "3")]
    pub recipients: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub nsfw: ::core::option::Option<bool>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsCreateResponse {
    #[prost(oneof = "groups_create_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<groups_create_response::Response>,
}
/// Nested message and enum types in `GroupsCreateResponse`.
pub mod groups_create_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::GroupsCreateResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsCreateResponseData {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsListRequest {
    #[prost(message, optional, tag = "1")]
    pub pagination: ::core::option::Option<super::super::shared::v1::PaginationRequest>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsListResponse {
    #[prost(oneof = "groups_list_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<groups_list_response::Response>,
}
/// Nested message and enum types in `GroupsListResponse`.
pub mod groups_list_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::GroupsListResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsListResponseData {
    #[prost(message, repeated, tag = "1")]
    pub groups: ::prost::alloc::vec::Vec<GroupsListItem>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::super::shared::v1::PaginationResponse>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupsListItem {
    /// channel id
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub group: ::core::option::Option<ChannelGroup>,
    #[prost(int64, tag = "3")]
    pub created_at: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersCreateRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersCreateResponse {
    #[prost(oneof = "users_create_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<users_create_response::Response>,
}
/// Nested message and enum types in `UsersCreateResponse`.
pub mod users_create_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::UsersCreateResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersCreateResponseData {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersLoginRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mfa: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub login_challenge: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersLoginResponse {
    #[prost(oneof = "users_login_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<users_login_response::Response>,
}
/// Nested message and enum types in `UsersLoginResponse`.
pub mod users_login_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::UsersLoginResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersLoginResponseData {
    #[prost(string, tag = "1")]
    pub redirect_to: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersEmailConfirmationRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersEmailConfirmationResponse {
    #[prost(oneof = "users_email_confirmation_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<users_email_confirmation_response::Response>,
}
/// Nested message and enum types in `UsersEmailConfirmationResponse`.
pub mod users_email_confirmation_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::UsersEmailConfirmationResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersEmailConfirmationResponseData {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersForgotPasswordRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersForgotPasswordResponse {
    #[prost(oneof = "users_forgot_password_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<users_forgot_password_response::Response>,
}
/// Nested message and enum types in `UsersForgotPasswordResponse`.
pub mod users_forgot_password_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::UsersForgotPasswordResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersForgotPasswordResponseData {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersResetPasswordRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password_confirmation: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersResetPasswordResponse {
    #[prost(oneof = "users_reset_password_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<users_reset_password_response::Response>,
}
/// Nested message and enum types in `UsersResetPasswordResponse`.
pub mod users_reset_password_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::UsersResetPasswordResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsersResetPasswordResponseData {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserFlag {
    Unspecified = 0,
    SuspendedUntil = 1,
    Deleted = 2,
    Banned = 4,
    Spam = 8,
}
impl UserFlag {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USER_FLAG_UNSPECIFIED",
            Self::SuspendedUntil => "USER_FLAG_SUSPENDED_UNTIL",
            Self::Deleted => "USER_FLAG_DELETED",
            Self::Banned => "USER_FLAG_BANNED",
            Self::Spam => "USER_FLAG_SPAM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_FLAG_UNSPECIFIED" => Some(Self::Unspecified),
            "USER_FLAG_SUSPENDED_UNTIL" => Some(Self::SuspendedUntil),
            "USER_FLAG_DELETED" => Some(Self::Deleted),
            "USER_FLAG_BANNED" => Some(Self::Banned),
            "USER_FLAG_SPAM" => Some(Self::Spam),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUsernamesRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUsernamesResponse {
    #[prost(oneof = "search_usernames_response::Response", tags = "1, 2")]
    pub response: ::core::option::Option<search_usernames_response::Response>,
}
/// Nested message and enum types in `SearchUsernamesResponse`.
pub mod search_usernames_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "1")]
        Data(super::SearchUsernamesResponseData),
        #[prost(message, tag = "2")]
        Error(super::super::super::shared::v1::AppError),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUsernamesResponseData {
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<SearchUser>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUser {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub avatar: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod chaty_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ChatyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ChatyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ChatyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ChatyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ChatyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn users_create(
            &mut self,
            request: impl tonic::IntoRequest<super::UsersCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersCreateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/UsersCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("service.v1.ChatyService", "UsersCreate"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn users_login(
            &mut self,
            request: impl tonic::IntoRequest<super::UsersLoginRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersLoginResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/UsersLogin",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("service.v1.ChatyService", "UsersLogin"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn users_email_confirmation(
            &mut self,
            request: impl tonic::IntoRequest<super::UsersEmailConfirmationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersEmailConfirmationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/UsersEmailConfirmation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("service.v1.ChatyService", "UsersEmailConfirmation"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn users_forgot_password(
            &mut self,
            request: impl tonic::IntoRequest<super::UsersForgotPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersForgotPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/UsersForgotPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("service.v1.ChatyService", "UsersForgotPassword"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn users_reset_password(
            &mut self,
            request: impl tonic::IntoRequest<super::UsersResetPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersResetPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/UsersResetPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("service.v1.ChatyService", "UsersResetPassword"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn groups_create(
            &mut self,
            request: impl tonic::IntoRequest<super::GroupsCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GroupsCreateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/GroupsCreate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("service.v1.ChatyService", "GroupsCreate"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn groups_list(
            &mut self,
            request: impl tonic::IntoRequest<super::GroupsListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GroupsListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/GroupsList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("service.v1.ChatyService", "GroupsList"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_usernames(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchUsernamesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchUsernamesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/service.v1.ChatyService/SearchUsernames",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("service.v1.ChatyService", "SearchUsernames"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod chaty_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ChatyServiceServer.
    #[async_trait]
    pub trait ChatyService: std::marker::Send + std::marker::Sync + 'static {
        async fn users_create(
            &self,
            request: tonic::Request<super::UsersCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersCreateResponse>,
            tonic::Status,
        >;
        async fn users_login(
            &self,
            request: tonic::Request<super::UsersLoginRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersLoginResponse>,
            tonic::Status,
        >;
        async fn users_email_confirmation(
            &self,
            request: tonic::Request<super::UsersEmailConfirmationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersEmailConfirmationResponse>,
            tonic::Status,
        >;
        async fn users_forgot_password(
            &self,
            request: tonic::Request<super::UsersForgotPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersForgotPasswordResponse>,
            tonic::Status,
        >;
        async fn users_reset_password(
            &self,
            request: tonic::Request<super::UsersResetPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UsersResetPasswordResponse>,
            tonic::Status,
        >;
        async fn groups_create(
            &self,
            request: tonic::Request<super::GroupsCreateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GroupsCreateResponse>,
            tonic::Status,
        >;
        async fn groups_list(
            &self,
            request: tonic::Request<super::GroupsListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GroupsListResponse>,
            tonic::Status,
        >;
        async fn search_usernames(
            &self,
            request: tonic::Request<super::SearchUsernamesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchUsernamesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct ChatyServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ChatyServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ChatyServiceServer<T>
    where
        T: ChatyService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/service.v1.ChatyService/UsersCreate" => {
                    #[allow(non_camel_case_types)]
                    struct UsersCreateSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::UsersCreateRequest>
                    for UsersCreateSvc<T> {
                        type Response = super::UsersCreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UsersCreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::users_create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UsersCreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/UsersLogin" => {
                    #[allow(non_camel_case_types)]
                    struct UsersLoginSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::UsersLoginRequest>
                    for UsersLoginSvc<T> {
                        type Response = super::UsersLoginResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UsersLoginRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::users_login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UsersLoginSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/UsersEmailConfirmation" => {
                    #[allow(non_camel_case_types)]
                    struct UsersEmailConfirmationSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::UsersEmailConfirmationRequest>
                    for UsersEmailConfirmationSvc<T> {
                        type Response = super::UsersEmailConfirmationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UsersEmailConfirmationRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::users_email_confirmation(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UsersEmailConfirmationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/UsersForgotPassword" => {
                    #[allow(non_camel_case_types)]
                    struct UsersForgotPasswordSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::UsersForgotPasswordRequest>
                    for UsersForgotPasswordSvc<T> {
                        type Response = super::UsersForgotPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UsersForgotPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::users_forgot_password(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UsersForgotPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/UsersResetPassword" => {
                    #[allow(non_camel_case_types)]
                    struct UsersResetPasswordSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::UsersResetPasswordRequest>
                    for UsersResetPasswordSvc<T> {
                        type Response = super::UsersResetPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UsersResetPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::users_reset_password(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UsersResetPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/GroupsCreate" => {
                    #[allow(non_camel_case_types)]
                    struct GroupsCreateSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::GroupsCreateRequest>
                    for GroupsCreateSvc<T> {
                        type Response = super::GroupsCreateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GroupsCreateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::groups_create(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GroupsCreateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/GroupsList" => {
                    #[allow(non_camel_case_types)]
                    struct GroupsListSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::GroupsListRequest>
                    for GroupsListSvc<T> {
                        type Response = super::GroupsListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GroupsListRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::groups_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GroupsListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/service.v1.ChatyService/SearchUsernames" => {
                    #[allow(non_camel_case_types)]
                    struct SearchUsernamesSvc<T: ChatyService>(pub Arc<T>);
                    impl<
                        T: ChatyService,
                    > tonic::server::UnaryService<super::SearchUsernamesRequest>
                    for SearchUsernamesSvc<T> {
                        type Response = super::SearchUsernamesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SearchUsernamesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as ChatyService>::search_usernames(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SearchUsernamesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ChatyServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "service.v1.ChatyService";
    impl<T> tonic::server::NamedService for ChatyServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// ===========================================
/// MESSAGE WEBHOOK
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageWebhook {
    /// The name of the webhook - 1 to 32 chars
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The id of the avatar of the webhook, if it has one (optional)
    #[prost(string, optional, tag = "2")]
    pub avatar: ::core::option::Option<::prost::alloc::string::String>,
}
/// ===========================================
/// SYSTEM MESSAGE (oneof for enum variants)
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystem {
    #[prost(
        oneof = "message_system::Type",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14"
    )]
    pub r#type: ::core::option::Option<message_system::Type>,
}
/// Nested message and enum types in `MessageSystem`.
pub mod message_system {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "1")]
        Text(super::MessageSystemText),
        #[prost(message, tag = "2")]
        UserAdded(super::MessageSystemUserAdded),
        #[prost(message, tag = "3")]
        UserRemove(super::MessageSystemUserRemove),
        #[prost(message, tag = "4")]
        UserJoined(super::MessageSystemUserJoined),
        #[prost(message, tag = "5")]
        UserLeft(super::MessageSystemUserLeft),
        #[prost(message, tag = "6")]
        UserKicked(super::MessageSystemUserKicked),
        #[prost(message, tag = "7")]
        UserBanned(super::MessageSystemUserBanned),
        #[prost(message, tag = "8")]
        ChannelRenamed(super::MessageSystemChannelRenamed),
        #[prost(message, tag = "9")]
        ChannelDescriptionChanged(super::MessageSystemChannelDescriptionChanged),
        #[prost(message, tag = "10")]
        ChannelIconChanged(super::MessageSystemChannelIconChanged),
        #[prost(message, tag = "11")]
        ChannelOwnershipChanged(super::MessageSystemChannelOwnershipChanged),
        #[prost(message, tag = "12")]
        MessagePinned(super::MessageSystemMessagePinned),
        #[prost(message, tag = "13")]
        MessageUnpinned(super::MessageSystemMessageUnpinned),
        #[prost(message, tag = "14")]
        CallStarted(super::MessageSystemCallStarted),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemText {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemUserAdded {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemUserRemove {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemUserJoined {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemUserLeft {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemUserKicked {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemUserBanned {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemChannelRenamed {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemChannelDescriptionChanged {
    #[prost(string, tag = "1")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemChannelIconChanged {
    #[prost(string, tag = "1")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemChannelOwnershipChanged {
    #[prost(string, tag = "1")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemMessagePinned {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemMessageUnpinned {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub by: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageSystemCallStarted {
    #[prost(string, tag = "1")]
    pub by: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub finished_at: i64,
}
/// Image
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedImage {
    /// URL to the original image
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    /// Width of the image
    #[prost(int32, tag = "2")]
    pub width: i32,
    /// Height of the image
    #[prost(int32, tag = "3")]
    pub height: i32,
    /// Positioning and size
    #[prost(enumeration = "ImageSize", tag = "4")]
    pub size: i32,
}
/// Video
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedVideo {
    /// URL to the original video
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    /// Width of the video
    #[prost(int32, tag = "2")]
    pub width: i32,
    /// Height of the video
    #[prost(int32, tag = "3")]
    pub height: i32,
}
/// Information about special remote content
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedWebsiteMetadataSpecial {
    #[prost(
        oneof = "embed_website_metadata_special::Type",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10"
    )]
    pub r#type: ::core::option::Option<embed_website_metadata_special::Type>,
}
/// Nested message and enum types in `EmbedWebsiteMetadataSpecial`.
pub mod embed_website_metadata_special {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        /// No remote content
        #[prost(message, tag = "1")]
        None(super::super::super::shared::v1::Empty),
        /// Content hint that this contains a GIF (use metadata to find video or image to play)
        #[prost(message, tag = "2")]
        Gif(super::super::super::shared::v1::Empty),
        /// YouTube video
        #[prost(message, tag = "3")]
        Youtube(super::EmbedYouTube),
        /// Lightspeed.tv stream
        #[prost(message, tag = "4")]
        Lightspeed(super::EmbedLightspeed),
        /// Twitch stream or clip
        #[prost(message, tag = "5")]
        Twitch(super::EmbedTwitch),
        /// Spotify track
        #[prost(message, tag = "6")]
        Spotify(super::EmbedSpotify),
        /// Soundcloud track
        #[prost(message, tag = "7")]
        Soundcloud(super::super::super::shared::v1::Empty),
        /// Bandcamp track
        #[prost(message, tag = "8")]
        Bandcamp(super::EmbedBandcamp),
        /// Apple Music
        #[prost(message, tag = "9")]
        AppleMusic(super::EmbedAppleMusic),
        /// Streamable Video
        #[prost(message, tag = "10")]
        Streamable(super::EmbedStreamable),
    }
}
/// YouTube video
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedYouTube {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost::alloc::string::String>,
}
/// Lightspeed.tv stream
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedLightspeed {
    #[prost(enumeration = "LightspeedType", tag = "1")]
    pub content_type: i32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
/// Twitch stream or clip
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedTwitch {
    #[prost(enumeration = "TwitchType", tag = "1")]
    pub content_type: i32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
/// Spotify track
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedSpotify {
    /// Free-form string
    #[prost(string, tag = "1")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
/// Bandcamp track
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedBandcamp {
    #[prost(enumeration = "BandcampType", tag = "1")]
    pub content_type: i32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
/// Apple Music
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedAppleMusic {
    #[prost(string, tag = "1")]
    pub album_id: ::prost::alloc::string::String,
    /// optional
    #[prost(string, tag = "2")]
    pub track_id: ::prost::alloc::string::String,
}
/// Streamable Video
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedStreamable {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// Website metadata
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedWebsiteMetadata {
    /// Direct URL to web page (optional)
    #[prost(string, optional, tag = "1")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    /// Original direct URL (optional)
    #[prost(string, optional, tag = "2")]
    pub original_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Remote content (optional)
    #[prost(message, optional, tag = "3")]
    pub special: ::core::option::Option<EmbedWebsiteMetadataSpecial>,
    /// Title of website (optional)
    #[prost(string, optional, tag = "4")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    /// Description of website (optional)
    #[prost(string, optional, tag = "5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Embedded image (optional)
    #[prost(message, optional, tag = "6")]
    pub image: ::core::option::Option<EmbedImage>,
    /// Embedded video (optional)
    #[prost(message, optional, tag = "7")]
    pub video: ::core::option::Option<EmbedVideo>,
    /// Site name (optional)
    #[prost(string, optional, tag = "8")]
    pub site_name: ::core::option::Option<::prost::alloc::string::String>,
    /// URL to site icon (optional)
    #[prost(string, optional, tag = "9")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    /// CSS Colour (optional)
    #[prost(string, optional, tag = "10")]
    pub colour: ::core::option::Option<::prost::alloc::string::String>,
}
/// Text Embed
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmbedText {
    /// URL to icon (optional)
    #[prost(string, optional, tag = "1")]
    pub icon_url: ::core::option::Option<::prost::alloc::string::String>,
    /// URL for title (optional)
    #[prost(string, optional, tag = "2")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    /// Title of text embed (optional)
    #[prost(string, optional, tag = "3")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    /// Description of text embed (optional)
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// ID of uploaded autumn file (optional)
    #[prost(message, optional, tag = "5")]
    pub media: ::core::option::Option<super::super::shared::v1::File>,
    /// CSS Colour (optional)
    #[prost(string, optional, tag = "6")]
    pub colour: ::core::option::Option<::prost::alloc::string::String>,
}
/// Embed (oneof for different embed types)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Embed {
    #[prost(oneof = "embed::Type", tags = "1, 2, 3, 4, 5")]
    pub r#type: ::core::option::Option<embed::Type>,
}
/// Nested message and enum types in `Embed`.
pub mod embed {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "1")]
        Website(super::EmbedWebsiteMetadata),
        #[prost(message, tag = "2")]
        Image(super::EmbedImage),
        #[prost(message, tag = "3")]
        Video(super::EmbedVideo),
        #[prost(message, tag = "4")]
        Text(super::EmbedText),
        #[prost(message, tag = "5")]
        None(super::super::super::shared::v1::Empty),
    }
}
/// ===========================================
/// INTERACTIONS
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Interactions {
    /// Reactions which should always appear and be distinct (optional)
    #[prost(string, repeated, tag = "1")]
    pub reactions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Whether reactions should be restricted to the given list
    #[prost(bool, tag = "2")]
    pub restrict_reactions: bool,
}
/// ===========================================
/// MASQUERADE
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Masquerade {
    /// Replace the display name shown on this message (optional)
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// Replace the avatar shown on this message (URL to image file) (optional)
    #[prost(string, optional, tag = "2")]
    pub avatar: ::core::option::Option<::prost::alloc::string::String>,
    /// Replace the display role colour shown on this message (optional)
    #[prost(string, optional, tag = "3")]
    pub colour: ::core::option::Option<::prost::alloc::string::String>,
}
/// ===========================================
/// MAIN MESSAGE
/// ===========================================
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// Unique Id
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Id of the channel this message was sent in
    #[prost(string, tag = "2")]
    pub channel_id: ::prost::alloc::string::String,
    /// Unique value generated by client sending this message (optional)
    #[prost(string, optional, tag = "3")]
    pub nonce: ::core::option::Option<::prost::alloc::string::String>,
    /// Id of the user or webhook that sent this message
    #[prost(string, tag = "4")]
    pub author_id: ::prost::alloc::string::String,
    /// The webhook that sent this message (optional)
    #[prost(message, optional, tag = "5")]
    pub webhook: ::core::option::Option<MessageWebhook>,
    /// Message content (optional)
    #[prost(string, optional, tag = "6")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
    /// System message (optional)
    #[prost(message, optional, tag = "7")]
    pub system: ::core::option::Option<MessageSystem>,
    /// Array of attachments (optional)
    #[prost(message, repeated, tag = "8")]
    pub attachments: ::prost::alloc::vec::Vec<super::super::shared::v1::File>,
    /// Bitfield of message flags (optional)
    #[prost(int32, optional, tag = "9")]
    pub flags: ::core::option::Option<i32>,
    /// Attached embeds to this message (optional)
    #[prost(message, repeated, tag = "10")]
    pub embeds: ::prost::alloc::vec::Vec<Embed>,
    /// Array of user ids mentioned in this message (optional)
    #[prost(string, repeated, tag = "11")]
    pub mentions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Array of role ids mentioned in this message (optional)
    #[prost(string, repeated, tag = "12")]
    pub role_mentions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Array of message ids this message is replying to (optional)
    #[prost(string, repeated, tag = "13")]
    pub replies: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Hashmap of emoji IDs to array of user IDs
    #[prost(map = "string, message", tag = "14")]
    pub reactions: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::super::shared::v1::StringArray,
    >,
    /// Information about how this message should be interacted with
    #[prost(message, optional, tag = "15")]
    pub interactions: ::core::option::Option<Interactions>,
    /// Name and / or avatar overrides for this message (optional)
    #[prost(message, optional, tag = "16")]
    pub masquerade: ::core::option::Option<Masquerade>,
    /// Whether or not the message is pinned (optional)
    #[prost(bool, optional, tag = "17")]
    pub pinned: ::core::option::Option<bool>,
    /// Time at which this message was last edited (optional)
    #[prost(int64, optional, tag = "18")]
    pub edited_at: ::core::option::Option<i64>,
    #[prost(int64, tag = "19")]
    pub created_at: i64,
}
/// Image positioning and size
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ImageSize {
    /// Show large preview at the bottom of the embed
    Large = 0,
    /// Show small preview to the side of the embed
    Preview = 1,
}
impl ImageSize {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Large => "LARGE",
            Self::Preview => "PREVIEW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LARGE" => Some(Self::Large),
            "PREVIEW" => Some(Self::Preview),
            _ => None,
        }
    }
}
/// Type of remote Twitch content
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TwitchType {
    TwitchChannel = 0,
    TwitchVideo = 1,
    TwitchClip = 2,
}
impl TwitchType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TwitchChannel => "TWITCH_CHANNEL",
            Self::TwitchVideo => "TWITCH_VIDEO",
            Self::TwitchClip => "TWITCH_CLIP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TWITCH_CHANNEL" => Some(Self::TwitchChannel),
            "TWITCH_VIDEO" => Some(Self::TwitchVideo),
            "TWITCH_CLIP" => Some(Self::TwitchClip),
            _ => None,
        }
    }
}
/// Type of remote Lightspeed.tv content
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LightspeedType {
    LightspeedChannel = 0,
}
impl LightspeedType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::LightspeedChannel => "LIGHTSPEED_CHANNEL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LIGHTSPEED_CHANNEL" => Some(Self::LightspeedChannel),
            _ => None,
        }
    }
}
/// Type of remote Bandcamp content
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BandcampType {
    BandcampAlbum = 0,
    BandcampTrack = 1,
}
impl BandcampType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BandcampAlbum => "BANDCAMP_ALBUM",
            Self::BandcampTrack => "BANDCAMP_TRACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BANDCAMP_ALBUM" => Some(Self::BandcampAlbum),
            "BANDCAMP_TRACK" => Some(Self::BandcampTrack),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMember {
    /// Server ID (partition key)
    #[prost(string, tag = "1")]
    pub server_id: ::prost::alloc::string::String,
    /// User ID
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    /// User info (denormalized)
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub avatar: ::core::option::Option<super::super::shared::v1::File>,
    /// Member-specific
    #[prost(string, optional, tag = "5")]
    pub nickname: ::core::option::Option<::prost::alloc::string::String>,
    /// Time at which this user joined the server
    #[prost(int64, tag = "6")]
    pub joined_at: i64,
    /// Role IDs assigned to this member
    #[prost(string, repeated, tag = "7")]
    pub roles: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Timestamp this member is timed out until
    #[prost(int64, optional, tag = "8")]
    pub timeout: ::core::option::Option<i64>,
    /// Voice settings
    #[prost(bool, tag = "9")]
    pub can_publish: bool,
    #[prost(bool, tag = "10")]
    pub can_receive: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Server {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// Description for the server
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Default set of server and channel permissions
    #[prost(int64, tag = "5")]
    pub default_permissions: i64,
    /// Icon attachment
    #[prost(message, optional, tag = "6")]
    pub icon: ::core::option::Option<super::super::shared::v1::File>,
    /// Banner attachment
    #[prost(message, optional, tag = "7")]
    pub banner: ::core::option::Option<super::super::shared::v1::File>,
    /// Bitfield of server flags
    #[prost(int32, optional, tag = "8")]
    pub flags: ::core::option::Option<i32>,
    /// Whether this server is flagged as not safe for work
    #[prost(bool, tag = "9")]
    pub nsfw: bool,
    /// Whether to enable analytics
    #[prost(bool, tag = "10")]
    pub analytics: bool,
    /// Whether this server should be publicly discoverable
    #[prost(bool, tag = "11")]
    pub discoverable: bool,
    /// Roles for this server
    #[prost(map = "string, message", tag = "12")]
    pub roles: ::std::collections::HashMap<::prost::alloc::string::String, Role>,
    /// Categories for this server
    #[prost(message, repeated, tag = "13")]
    pub categories: ::prost::alloc::vec::Vec<Category>,
    /// Configuration for sending system event messages
    #[prost(message, optional, tag = "14")]
    pub system_messages: ::core::option::Option<ServerSystemMessagesChannels>,
    #[prost(message, optional, tag = "15")]
    pub stats: ::core::option::Option<ServerStats>,
    /// Channels within this server
    #[prost(string, repeated, tag = "16")]
    pub channels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, tag = "17")]
    pub created_at: i64,
    #[prost(int64, tag = "18")]
    pub updated_at: i64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Category {
    /// Unique ID for this category (1-32 chars)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Title for this category (1-32 chars)
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    /// Channels in this category
    #[prost(string, repeated, tag = "3")]
    pub channels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerSystemMessagesChannels {
    /// ID of channel to send user join messages in (optional)
    #[prost(string, optional, tag = "1")]
    pub user_joined: ::core::option::Option<::prost::alloc::string::String>,
    /// ID of channel to send user left messages in (optional)
    #[prost(string, optional, tag = "2")]
    pub user_left: ::core::option::Option<::prost::alloc::string::String>,
    /// ID of channel to send user kicked messages in (optional)
    #[prost(string, optional, tag = "3")]
    pub user_kicked: ::core::option::Option<::prost::alloc::string::String>,
    /// ID of channel to send user banned messages in (optional)
    #[prost(string, optional, tag = "4")]
    pub user_banned: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(scylla::SerializeValue, scylla::DeserializeValue)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ServerStats {
    #[prost(int32, tag = "1")]
    pub members_count: i32,
    #[prost(int32, tag = "2")]
    pub channels_count: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    /// ulid
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 64 char
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// 255 char
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub password: ::prost::alloc::string::String,
    /// 64 char
    #[prost(string, optional, tag = "5")]
    pub display_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "6")]
    pub badges: ::core::option::Option<i32>,
    /// 510 char
    #[prost(string, optional, tag = "7")]
    pub status_text: ::core::option::Option<::prost::alloc::string::String>,
    /// 32 char
    #[prost(enumeration = "UserStatus", optional, tag = "8")]
    pub status_presence: ::core::option::Option<i32>,
    /// text
    #[prost(string, optional, tag = "9")]
    pub profile_content: ::core::option::Option<::prost::alloc::string::String>,
    /// ulid (26 chars) Reference to files collection
    #[prost(string, optional, tag = "10")]
    pub profile_background_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "11")]
    pub privileged: bool,
    #[prost(int64, optional, tag = "12")]
    pub suspended_until: ::core::option::Option<i64>,
    /// unix timestamp miliseconds
    #[prost(int64, tag = "13")]
    pub created_at: i64,
    /// unix timestamp miliseconds
    #[prost(int64, tag = "14")]
    pub updated_at: i64,
    #[prost(bool, tag = "15")]
    pub verified: bool,
    #[prost(message, optional, tag = "16")]
    pub avatar: ::core::option::Option<super::super::shared::v1::File>,
    #[prost(message, repeated, tag = "17")]
    pub relations: ::prost::alloc::vec::Vec<UserRelationship>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserRelationship {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "UserRelationshipStatus", tag = "2")]
    pub status: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserStatus {
    Online = 0,
    Idle = 1,
    Focus = 2,
    Busy = 3,
    Invisible = 4,
}
impl UserStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Online => "USER_STATUS_ONLINE",
            Self::Idle => "USER_STATUS_IDLE",
            Self::Focus => "USER_STATUS_FOCUS",
            Self::Busy => "USER_STATUS_BUSY",
            Self::Invisible => "USER_STATUS_INVISIBLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_STATUS_ONLINE" => Some(Self::Online),
            "USER_STATUS_IDLE" => Some(Self::Idle),
            "USER_STATUS_FOCUS" => Some(Self::Focus),
            "USER_STATUS_BUSY" => Some(Self::Busy),
            "USER_STATUS_INVISIBLE" => Some(Self::Invisible),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserRelationshipStatus {
    None = 0,
    /// Self
    User = 1,
    Friend = 2,
    /// Friend request sent
    Outgoing = 3,
    /// Friend request received
    Incoming = 4,
    /// You blocked them
    Blocked = 5,
    /// They blocked you
    BlockedOther = 6,
}
impl UserRelationshipStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "USER_RELATIONSHIP_STATUS_NONE",
            Self::User => "USER_RELATIONSHIP_STATUS_USER",
            Self::Friend => "USER_RELATIONSHIP_STATUS_FRIEND",
            Self::Outgoing => "USER_RELATIONSHIP_STATUS_OUTGOING",
            Self::Incoming => "USER_RELATIONSHIP_STATUS_INCOMING",
            Self::Blocked => "USER_RELATIONSHIP_STATUS_BLOCKED",
            Self::BlockedOther => "USER_RELATIONSHIP_STATUS_BLOCKED_OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_RELATIONSHIP_STATUS_NONE" => Some(Self::None),
            "USER_RELATIONSHIP_STATUS_USER" => Some(Self::User),
            "USER_RELATIONSHIP_STATUS_FRIEND" => Some(Self::Friend),
            "USER_RELATIONSHIP_STATUS_OUTGOING" => Some(Self::Outgoing),
            "USER_RELATIONSHIP_STATUS_INCOMING" => Some(Self::Incoming),
            "USER_RELATIONSHIP_STATUS_BLOCKED" => Some(Self::Blocked),
            "USER_RELATIONSHIP_STATUS_BLOCKED_OTHER" => Some(Self::BlockedOther),
            _ => None,
        }
    }
}
