// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AppError {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// displayed to the end user without debugging info
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// Internal debug info
    #[prost(string, tag = "3")]
    pub detailed_error: ::prost::alloc::string::String,
    /// grpc status code
    #[prost(uint32, tag = "5")]
    pub status_code: u32,
    /// Code path or func name
    #[prost(string, tag = "6")]
    pub location: ::prost::alloc::string::String,
    /// If false, i18n may not apply
    #[prost(bool, optional, tag = "7")]
    pub skip_translation: ::core::option::Option<bool>,
    #[prost(map = "string, string", tag = "8")]
    pub errors: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
