// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/channels.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error";
import { Channel } from "./channels_db";

export const protobufPackage = "service.v1";

/** Channel Unread */
export interface ChannelUnread {
  id?:
    | ChannelCompositeKey
    | undefined;
  /** Id of the last message read in this channel by a user */
  lastId?:
    | string
    | undefined;
  /** Array of message ids that mention the user */
  mentions: string[];
}

/** Composite primary key consisting of channel and user id */
export interface ChannelCompositeKey {
  /** @description Channel Id */
  channel: string;
  /** @description User Id */
  user: string;
}

export interface ChannelsGetRequest {
  /** channel id */
  id: string;
}

export interface ChannelsGetResponse {
  data?: Channel | undefined;
  error?: AppError | undefined;
}

export interface ChannelsCreateRequest {
  /** Channel type (voice or text) */
  channelType: string;
  /**
   * Channel name
   * Validation: length(min = 1, max = 32)
   */
  name: string;
  /**
   * Channel description
   * Validation: length(min = 0, max = 1024)
   */
  description?:
    | string
    | undefined;
  /** Whether this channel is age restricted */
  nsfw?:
    | boolean
    | undefined;
  /** Voice Information for when this channel is also a voice channel */
  voiceMaxUsers?: number | undefined;
}

export interface ChannelsCreateResponse {
}

function createBaseChannelUnread(): ChannelUnread {
  return { id: undefined, lastId: undefined, mentions: [] };
}

export const ChannelUnread: MessageFns<ChannelUnread> = {
  encode(message: ChannelUnread, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined) {
      ChannelCompositeKey.encode(message.id, writer.uint32(10).fork()).join();
    }
    if (message.lastId !== undefined) {
      writer.uint32(18).string(message.lastId);
    }
    for (const v of message.mentions) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelUnread {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelUnread();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = ChannelCompositeKey.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mentions.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelUnread {
    return {
      id: isSet(object.id) ? ChannelCompositeKey.fromJSON(object.id) : undefined,
      lastId: isSet(object.lastId) ? globalThis.String(object.lastId) : undefined,
      mentions: globalThis.Array.isArray(object?.mentions) ? object.mentions.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: ChannelUnread): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = ChannelCompositeKey.toJSON(message.id);
    }
    if (message.lastId !== undefined) {
      obj.lastId = message.lastId;
    }
    if (message.mentions?.length) {
      obj.mentions = message.mentions;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelUnread>, I>>(base?: I): ChannelUnread {
    return ChannelUnread.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelUnread>, I>>(object: I): ChannelUnread {
    const message = createBaseChannelUnread();
    message.id = (object.id !== undefined && object.id !== null)
      ? ChannelCompositeKey.fromPartial(object.id)
      : undefined;
    message.lastId = object.lastId ?? undefined;
    message.mentions = object.mentions?.map((e) => e) || [];
    return message;
  },
};

function createBaseChannelCompositeKey(): ChannelCompositeKey {
  return { channel: "", user: "" };
}

export const ChannelCompositeKey: MessageFns<ChannelCompositeKey> = {
  encode(message: ChannelCompositeKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channel !== "") {
      writer.uint32(10).string(message.channel);
    }
    if (message.user !== "") {
      writer.uint32(18).string(message.user);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelCompositeKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelCompositeKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelCompositeKey {
    return {
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      user: isSet(object.user) ? globalThis.String(object.user) : "",
    };
  },

  toJSON(message: ChannelCompositeKey): unknown {
    const obj: any = {};
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.user !== "") {
      obj.user = message.user;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelCompositeKey>, I>>(base?: I): ChannelCompositeKey {
    return ChannelCompositeKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelCompositeKey>, I>>(object: I): ChannelCompositeKey {
    const message = createBaseChannelCompositeKey();
    message.channel = object.channel ?? "";
    message.user = object.user ?? "";
    return message;
  },
};

function createBaseChannelsGetRequest(): ChannelsGetRequest {
  return { id: "" };
}

export const ChannelsGetRequest: MessageFns<ChannelsGetRequest> = {
  encode(message: ChannelsGetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelsGetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelsGetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelsGetRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: ChannelsGetRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelsGetRequest>, I>>(base?: I): ChannelsGetRequest {
    return ChannelsGetRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelsGetRequest>, I>>(object: I): ChannelsGetRequest {
    const message = createBaseChannelsGetRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseChannelsGetResponse(): ChannelsGetResponse {
  return { data: undefined, error: undefined };
}

export const ChannelsGetResponse: MessageFns<ChannelsGetResponse> = {
  encode(message: ChannelsGetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      Channel.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelsGetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelsGetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = Channel.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelsGetResponse {
    return {
      data: isSet(object.data) ? Channel.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ChannelsGetResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = Channel.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelsGetResponse>, I>>(base?: I): ChannelsGetResponse {
    return ChannelsGetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelsGetResponse>, I>>(object: I): ChannelsGetResponse {
    const message = createBaseChannelsGetResponse();
    message.data = (object.data !== undefined && object.data !== null) ? Channel.fromPartial(object.data) : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseChannelsCreateRequest(): ChannelsCreateRequest {
  return { channelType: "", name: "", description: undefined, nsfw: undefined, voiceMaxUsers: undefined };
}

export const ChannelsCreateRequest: MessageFns<ChannelsCreateRequest> = {
  encode(message: ChannelsCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channelType !== "") {
      writer.uint32(10).string(message.channelType);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.nsfw !== undefined) {
      writer.uint32(32).bool(message.nsfw);
    }
    if (message.voiceMaxUsers !== undefined) {
      writer.uint32(40).uint32(message.voiceMaxUsers);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelsCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelsCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channelType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.nsfw = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.voiceMaxUsers = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelsCreateRequest {
    return {
      channelType: isSet(object.channelType) ? globalThis.String(object.channelType) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      nsfw: isSet(object.nsfw) ? globalThis.Boolean(object.nsfw) : undefined,
      voiceMaxUsers: isSet(object.voiceMaxUsers) ? globalThis.Number(object.voiceMaxUsers) : undefined,
    };
  },

  toJSON(message: ChannelsCreateRequest): unknown {
    const obj: any = {};
    if (message.channelType !== "") {
      obj.channelType = message.channelType;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.nsfw !== undefined) {
      obj.nsfw = message.nsfw;
    }
    if (message.voiceMaxUsers !== undefined) {
      obj.voiceMaxUsers = Math.round(message.voiceMaxUsers);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelsCreateRequest>, I>>(base?: I): ChannelsCreateRequest {
    return ChannelsCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelsCreateRequest>, I>>(object: I): ChannelsCreateRequest {
    const message = createBaseChannelsCreateRequest();
    message.channelType = object.channelType ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.nsfw = object.nsfw ?? undefined;
    message.voiceMaxUsers = object.voiceMaxUsers ?? undefined;
    return message;
  },
};

function createBaseChannelsCreateResponse(): ChannelsCreateResponse {
  return {};
}

export const ChannelsCreateResponse: MessageFns<ChannelsCreateResponse> = {
  encode(_: ChannelsCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelsCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelsCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ChannelsCreateResponse {
    return {};
  },

  toJSON(_: ChannelsCreateResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelsCreateResponse>, I>>(base?: I): ChannelsCreateResponse {
    return ChannelsCreateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelsCreateResponse>, I>>(_: I): ChannelsCreateResponse {
    const message = createBaseChannelsCreateResponse();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
