// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/voice.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "service.v1";

/** / Voice State information for a user */
export interface UserVoiceState {
  id: string;
  joinedAt: bigint;
  isReceiving: boolean;
  isPublishing: boolean;
  screensharing: boolean;
  camera: boolean;
}

export interface ChannelVoiceState {
  id: string;
  /** The states of the users who are connected to the channel */
  participants: UserVoiceState[];
}

function createBaseUserVoiceState(): UserVoiceState {
  return { id: "", joinedAt: 0n, isReceiving: false, isPublishing: false, screensharing: false, camera: false };
}

export const UserVoiceState: MessageFns<UserVoiceState> = {
  encode(message: UserVoiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.joinedAt !== 0n) {
      if (BigInt.asIntN(64, message.joinedAt) !== message.joinedAt) {
        throw new globalThis.Error("value provided for field message.joinedAt of type int64 too large");
      }
      writer.uint32(16).int64(message.joinedAt);
    }
    if (message.isReceiving !== false) {
      writer.uint32(24).bool(message.isReceiving);
    }
    if (message.isPublishing !== false) {
      writer.uint32(32).bool(message.isPublishing);
    }
    if (message.screensharing !== false) {
      writer.uint32(40).bool(message.screensharing);
    }
    if (message.camera !== false) {
      writer.uint32(48).bool(message.camera);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserVoiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserVoiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.joinedAt = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isReceiving = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isPublishing = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.screensharing = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.camera = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserVoiceState {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      joinedAt: isSet(object.joinedAt) ? BigInt(object.joinedAt) : 0n,
      isReceiving: isSet(object.isReceiving) ? globalThis.Boolean(object.isReceiving) : false,
      isPublishing: isSet(object.isPublishing) ? globalThis.Boolean(object.isPublishing) : false,
      screensharing: isSet(object.screensharing) ? globalThis.Boolean(object.screensharing) : false,
      camera: isSet(object.camera) ? globalThis.Boolean(object.camera) : false,
    };
  },

  toJSON(message: UserVoiceState): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.joinedAt !== 0n) {
      obj.joinedAt = message.joinedAt.toString();
    }
    if (message.isReceiving !== false) {
      obj.isReceiving = message.isReceiving;
    }
    if (message.isPublishing !== false) {
      obj.isPublishing = message.isPublishing;
    }
    if (message.screensharing !== false) {
      obj.screensharing = message.screensharing;
    }
    if (message.camera !== false) {
      obj.camera = message.camera;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserVoiceState>, I>>(base?: I): UserVoiceState {
    return UserVoiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserVoiceState>, I>>(object: I): UserVoiceState {
    const message = createBaseUserVoiceState();
    message.id = object.id ?? "";
    message.joinedAt = object.joinedAt ?? 0n;
    message.isReceiving = object.isReceiving ?? false;
    message.isPublishing = object.isPublishing ?? false;
    message.screensharing = object.screensharing ?? false;
    message.camera = object.camera ?? false;
    return message;
  },
};

function createBaseChannelVoiceState(): ChannelVoiceState {
  return { id: "", participants: [] };
}

export const ChannelVoiceState: MessageFns<ChannelVoiceState> = {
  encode(message: ChannelVoiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    for (const v of message.participants) {
      UserVoiceState.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelVoiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelVoiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.participants.push(UserVoiceState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelVoiceState {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      participants: globalThis.Array.isArray(object?.participants)
        ? object.participants.map((e: any) => UserVoiceState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ChannelVoiceState): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.participants?.length) {
      obj.participants = message.participants.map((e) => UserVoiceState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelVoiceState>, I>>(base?: I): ChannelVoiceState {
    return ChannelVoiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelVoiceState>, I>>(object: I): ChannelVoiceState {
    const message = createBaseChannelVoiceState();
    message.id = object.id ?? "";
    message.participants = object.participants?.map((e) => UserVoiceState.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
