// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/channels_db.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { File } from "../../shared/v1/files.js";
import { Timestamp } from "../../shared/v1/time.js";

export const protobufPackage = "service.v1";

/**
 * ===========================================
 * OVERRIDE FIELD TYPE (permissions)
 * ===========================================
 */
export interface OverrideField {
  /** Allowed permissions */
  allow: string;
  /** Denied permissions */
  deny: string;
}

/** Group channel type */
export interface ChannelGroup {
  /** User id of the owner of the group */
  userId: string;
  /** Display name of the channel */
  name: string;
  /** Channel description */
  description?:
    | string
    | undefined;
  /** Array of user ids participating in channel */
  recipients: string[];
  /** Custom icon attachment */
  icon?:
    | File
    | undefined;
  /** Id of the last message sent in this channel */
  lastMessageId?:
    | string
    | undefined;
  /** Permissions assigned to members of this group (does not apply to owner) */
  permissions?:
    | string
    | undefined;
  /** Whether this group is marked as not safe for work */
  nsfw: boolean;
}

/** Saved messages channel type */
export interface ChannelSavedMessages {
  /** Id of the user this channel belongs to */
  userId: string;
}

/** Text channel type */
export interface ChannelText {
  /** Id of the server this channel belongs to */
  serverId: string;
  /** Display name of the channel */
  name: string;
  /** Channel description (optional) */
  description?:
    | string
    | undefined;
  /** Custom icon attachment (optional) */
  icon?:
    | File
    | undefined;
  /** Id of the last message sent in this channel (optional) */
  lastMessageId?:
    | string
    | undefined;
  /** Default permissions assigned to users in this channel (optional) */
  defaultPermissions?:
    | OverrideField
    | undefined;
  /** Map of role_id -> permissions */
  rolePermissions: { [key: string]: OverrideField };
  /** Whether this channel is marked as not safe for work */
  nsfw: boolean;
}

export interface ChannelText_RolePermissionsEntry {
  key: string;
  value?: OverrideField | undefined;
}

/** Direct message channel type */
export interface ChannelDirectMessage {
  /** Whether this direct message channel is currently open on both sides */
  active: boolean;
  /** 2-tuple of user ids participating in direct message */
  recipients: string[];
  /** Id of the last message sent in this channel */
  lastMessageId?: string | undefined;
}

/**
 * ===========================================
 * MAIN CHANNELS TABLE
 * ===========================================
 */
export interface Channel {
  /** ULID */
  id: string;
  /** 'saved_messages', 'direct_message', 'group', 'text_channel' */
  channelType: string;
  saved?: ChannelSavedMessages | undefined;
  direct?: ChannelDirectMessage | undefined;
  group?: ChannelGroup | undefined;
  text?:
    | ChannelText
    | undefined;
  /** Maximum users allowed in voice channel */
  voiceMaxUsers?: number | undefined;
  createdAt?: Timestamp | undefined;
  updatedAt?: Timestamp | undefined;
}

function createBaseOverrideField(): OverrideField {
  return { allow: "0", deny: "0" };
}

export const OverrideField: MessageFns<OverrideField> = {
  encode(message: OverrideField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allow !== "0") {
      writer.uint32(8).int64(message.allow);
    }
    if (message.deny !== "0") {
      writer.uint32(16).int64(message.deny);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OverrideField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOverrideField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.allow = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deny = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OverrideField {
    return {
      allow: isSet(object.allow) ? globalThis.String(object.allow) : "0",
      deny: isSet(object.deny) ? globalThis.String(object.deny) : "0",
    };
  },

  toJSON(message: OverrideField): unknown {
    const obj: any = {};
    if (message.allow !== "0") {
      obj.allow = message.allow;
    }
    if (message.deny !== "0") {
      obj.deny = message.deny;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OverrideField>, I>>(base?: I): OverrideField {
    return OverrideField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OverrideField>, I>>(object: I): OverrideField {
    const message = createBaseOverrideField();
    message.allow = object.allow ?? "0";
    message.deny = object.deny ?? "0";
    return message;
  },
};

function createBaseChannelGroup(): ChannelGroup {
  return {
    userId: "",
    name: "",
    description: undefined,
    recipients: [],
    icon: undefined,
    lastMessageId: undefined,
    permissions: undefined,
    nsfw: false,
  };
}

export const ChannelGroup: MessageFns<ChannelGroup> = {
  encode(message: ChannelGroup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    for (const v of message.recipients) {
      writer.uint32(34).string(v!);
    }
    if (message.icon !== undefined) {
      File.encode(message.icon, writer.uint32(42).fork()).join();
    }
    if (message.lastMessageId !== undefined) {
      writer.uint32(50).string(message.lastMessageId);
    }
    if (message.permissions !== undefined) {
      writer.uint32(56).int64(message.permissions);
    }
    if (message.nsfw !== false) {
      writer.uint32(64).bool(message.nsfw);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelGroup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelGroup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.recipients.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.icon = File.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.lastMessageId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.permissions = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.nsfw = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelGroup {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      recipients: globalThis.Array.isArray(object?.recipients)
        ? object.recipients.map((e: any) => globalThis.String(e))
        : [],
      icon: isSet(object.icon) ? File.fromJSON(object.icon) : undefined,
      lastMessageId: isSet(object.lastMessageId) ? globalThis.String(object.lastMessageId) : undefined,
      permissions: isSet(object.permissions) ? globalThis.String(object.permissions) : undefined,
      nsfw: isSet(object.nsfw) ? globalThis.Boolean(object.nsfw) : false,
    };
  },

  toJSON(message: ChannelGroup): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.recipients?.length) {
      obj.recipients = message.recipients;
    }
    if (message.icon !== undefined) {
      obj.icon = File.toJSON(message.icon);
    }
    if (message.lastMessageId !== undefined) {
      obj.lastMessageId = message.lastMessageId;
    }
    if (message.permissions !== undefined) {
      obj.permissions = message.permissions;
    }
    if (message.nsfw !== false) {
      obj.nsfw = message.nsfw;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelGroup>, I>>(base?: I): ChannelGroup {
    return ChannelGroup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelGroup>, I>>(object: I): ChannelGroup {
    const message = createBaseChannelGroup();
    message.userId = object.userId ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.recipients = object.recipients?.map((e) => e) || [];
    message.icon = (object.icon !== undefined && object.icon !== null) ? File.fromPartial(object.icon) : undefined;
    message.lastMessageId = object.lastMessageId ?? undefined;
    message.permissions = object.permissions ?? undefined;
    message.nsfw = object.nsfw ?? false;
    return message;
  },
};

function createBaseChannelSavedMessages(): ChannelSavedMessages {
  return { userId: "" };
}

export const ChannelSavedMessages: MessageFns<ChannelSavedMessages> = {
  encode(message: ChannelSavedMessages, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelSavedMessages {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelSavedMessages();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelSavedMessages {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: ChannelSavedMessages): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelSavedMessages>, I>>(base?: I): ChannelSavedMessages {
    return ChannelSavedMessages.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelSavedMessages>, I>>(object: I): ChannelSavedMessages {
    const message = createBaseChannelSavedMessages();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseChannelText(): ChannelText {
  return {
    serverId: "",
    name: "",
    description: undefined,
    icon: undefined,
    lastMessageId: undefined,
    defaultPermissions: undefined,
    rolePermissions: {},
    nsfw: false,
  };
}

export const ChannelText: MessageFns<ChannelText> = {
  encode(message: ChannelText, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.icon !== undefined) {
      File.encode(message.icon, writer.uint32(34).fork()).join();
    }
    if (message.lastMessageId !== undefined) {
      writer.uint32(42).string(message.lastMessageId);
    }
    if (message.defaultPermissions !== undefined) {
      OverrideField.encode(message.defaultPermissions, writer.uint32(50).fork()).join();
    }
    Object.entries(message.rolePermissions).forEach(([key, value]) => {
      ChannelText_RolePermissionsEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
    });
    if (message.nsfw !== false) {
      writer.uint32(64).bool(message.nsfw);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelText {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelText();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = File.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lastMessageId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.defaultPermissions = OverrideField.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = ChannelText_RolePermissionsEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.rolePermissions[entry7.key] = entry7.value;
          }
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.nsfw = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelText {
    return {
      serverId: isSet(object.serverId) ? globalThis.String(object.serverId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      icon: isSet(object.icon) ? File.fromJSON(object.icon) : undefined,
      lastMessageId: isSet(object.lastMessageId) ? globalThis.String(object.lastMessageId) : undefined,
      defaultPermissions: isSet(object.defaultPermissions)
        ? OverrideField.fromJSON(object.defaultPermissions)
        : undefined,
      rolePermissions: isObject(object.rolePermissions)
        ? Object.entries(object.rolePermissions).reduce<{ [key: string]: OverrideField }>((acc, [key, value]) => {
          acc[key] = OverrideField.fromJSON(value);
          return acc;
        }, {})
        : {},
      nsfw: isSet(object.nsfw) ? globalThis.Boolean(object.nsfw) : false,
    };
  },

  toJSON(message: ChannelText): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.icon !== undefined) {
      obj.icon = File.toJSON(message.icon);
    }
    if (message.lastMessageId !== undefined) {
      obj.lastMessageId = message.lastMessageId;
    }
    if (message.defaultPermissions !== undefined) {
      obj.defaultPermissions = OverrideField.toJSON(message.defaultPermissions);
    }
    if (message.rolePermissions) {
      const entries = Object.entries(message.rolePermissions);
      if (entries.length > 0) {
        obj.rolePermissions = {};
        entries.forEach(([k, v]) => {
          obj.rolePermissions[k] = OverrideField.toJSON(v);
        });
      }
    }
    if (message.nsfw !== false) {
      obj.nsfw = message.nsfw;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelText>, I>>(base?: I): ChannelText {
    return ChannelText.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelText>, I>>(object: I): ChannelText {
    const message = createBaseChannelText();
    message.serverId = object.serverId ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.icon = (object.icon !== undefined && object.icon !== null) ? File.fromPartial(object.icon) : undefined;
    message.lastMessageId = object.lastMessageId ?? undefined;
    message.defaultPermissions = (object.defaultPermissions !== undefined && object.defaultPermissions !== null)
      ? OverrideField.fromPartial(object.defaultPermissions)
      : undefined;
    message.rolePermissions = Object.entries(object.rolePermissions ?? {}).reduce<{ [key: string]: OverrideField }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = OverrideField.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.nsfw = object.nsfw ?? false;
    return message;
  },
};

function createBaseChannelText_RolePermissionsEntry(): ChannelText_RolePermissionsEntry {
  return { key: "", value: undefined };
}

export const ChannelText_RolePermissionsEntry: MessageFns<ChannelText_RolePermissionsEntry> = {
  encode(message: ChannelText_RolePermissionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      OverrideField.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelText_RolePermissionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelText_RolePermissionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = OverrideField.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelText_RolePermissionsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? OverrideField.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ChannelText_RolePermissionsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = OverrideField.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelText_RolePermissionsEntry>, I>>(
    base?: I,
  ): ChannelText_RolePermissionsEntry {
    return ChannelText_RolePermissionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelText_RolePermissionsEntry>, I>>(
    object: I,
  ): ChannelText_RolePermissionsEntry {
    const message = createBaseChannelText_RolePermissionsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? OverrideField.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseChannelDirectMessage(): ChannelDirectMessage {
  return { active: false, recipients: [], lastMessageId: undefined };
}

export const ChannelDirectMessage: MessageFns<ChannelDirectMessage> = {
  encode(message: ChannelDirectMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.active !== false) {
      writer.uint32(8).bool(message.active);
    }
    for (const v of message.recipients) {
      writer.uint32(18).string(v!);
    }
    if (message.lastMessageId !== undefined) {
      writer.uint32(26).string(message.lastMessageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChannelDirectMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannelDirectMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.recipients.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastMessageId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChannelDirectMessage {
    return {
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      recipients: globalThis.Array.isArray(object?.recipients)
        ? object.recipients.map((e: any) => globalThis.String(e))
        : [],
      lastMessageId: isSet(object.lastMessageId) ? globalThis.String(object.lastMessageId) : undefined,
    };
  },

  toJSON(message: ChannelDirectMessage): unknown {
    const obj: any = {};
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.recipients?.length) {
      obj.recipients = message.recipients;
    }
    if (message.lastMessageId !== undefined) {
      obj.lastMessageId = message.lastMessageId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChannelDirectMessage>, I>>(base?: I): ChannelDirectMessage {
    return ChannelDirectMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChannelDirectMessage>, I>>(object: I): ChannelDirectMessage {
    const message = createBaseChannelDirectMessage();
    message.active = object.active ?? false;
    message.recipients = object.recipients?.map((e) => e) || [];
    message.lastMessageId = object.lastMessageId ?? undefined;
    return message;
  },
};

function createBaseChannel(): Channel {
  return {
    id: "",
    channelType: "",
    saved: undefined,
    direct: undefined,
    group: undefined,
    text: undefined,
    voiceMaxUsers: undefined,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const Channel: MessageFns<Channel> = {
  encode(message: Channel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.channelType !== "") {
      writer.uint32(18).string(message.channelType);
    }
    if (message.saved !== undefined) {
      ChannelSavedMessages.encode(message.saved, writer.uint32(26).fork()).join();
    }
    if (message.direct !== undefined) {
      ChannelDirectMessage.encode(message.direct, writer.uint32(34).fork()).join();
    }
    if (message.group !== undefined) {
      ChannelGroup.encode(message.group, writer.uint32(42).fork()).join();
    }
    if (message.text !== undefined) {
      ChannelText.encode(message.text, writer.uint32(50).fork()).join();
    }
    if (message.voiceMaxUsers !== undefined) {
      writer.uint32(56).int32(message.voiceMaxUsers);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(message.createdAt, writer.uint32(66).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(message.updatedAt, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Channel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChannel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channelType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.saved = ChannelSavedMessages.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.direct = ChannelDirectMessage.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.group = ChannelGroup.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.text = ChannelText.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.voiceMaxUsers = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.updatedAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Channel {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      channelType: isSet(object.channelType) ? globalThis.String(object.channelType) : "",
      saved: isSet(object.saved) ? ChannelSavedMessages.fromJSON(object.saved) : undefined,
      direct: isSet(object.direct) ? ChannelDirectMessage.fromJSON(object.direct) : undefined,
      group: isSet(object.group) ? ChannelGroup.fromJSON(object.group) : undefined,
      text: isSet(object.text) ? ChannelText.fromJSON(object.text) : undefined,
      voiceMaxUsers: isSet(object.voiceMaxUsers) ? globalThis.Number(object.voiceMaxUsers) : undefined,
      createdAt: isSet(object.createdAt) ? Timestamp.fromJSON(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? Timestamp.fromJSON(object.updatedAt) : undefined,
    };
  },

  toJSON(message: Channel): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.channelType !== "") {
      obj.channelType = message.channelType;
    }
    if (message.saved !== undefined) {
      obj.saved = ChannelSavedMessages.toJSON(message.saved);
    }
    if (message.direct !== undefined) {
      obj.direct = ChannelDirectMessage.toJSON(message.direct);
    }
    if (message.group !== undefined) {
      obj.group = ChannelGroup.toJSON(message.group);
    }
    if (message.text !== undefined) {
      obj.text = ChannelText.toJSON(message.text);
    }
    if (message.voiceMaxUsers !== undefined) {
      obj.voiceMaxUsers = Math.round(message.voiceMaxUsers);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = Timestamp.toJSON(message.createdAt);
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = Timestamp.toJSON(message.updatedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Channel>, I>>(base?: I): Channel {
    return Channel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Channel>, I>>(object: I): Channel {
    const message = createBaseChannel();
    message.id = object.id ?? "";
    message.channelType = object.channelType ?? "";
    message.saved = (object.saved !== undefined && object.saved !== null)
      ? ChannelSavedMessages.fromPartial(object.saved)
      : undefined;
    message.direct = (object.direct !== undefined && object.direct !== null)
      ? ChannelDirectMessage.fromPartial(object.direct)
      : undefined;
    message.group = (object.group !== undefined && object.group !== null)
      ? ChannelGroup.fromPartial(object.group)
      : undefined;
    message.text = (object.text !== undefined && object.text !== null)
      ? ChannelText.fromPartial(object.text)
      : undefined;
    message.voiceMaxUsers = object.voiceMaxUsers ?? undefined;
    message.createdAt = (object.createdAt !== undefined && object.createdAt !== null)
      ? Timestamp.fromPartial(object.createdAt)
      : undefined;
    message.updatedAt = (object.updatedAt !== undefined && object.updatedAt !== null)
      ? Timestamp.fromPartial(object.updatedAt)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
