// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/groups.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";
import { PaginationRequest, PaginationResponse } from "../../shared/v1/pagination.js";
import { ChannelGroup } from "./channels_db.js";

export const protobufPackage = "service.v1";

export interface GroupsCreateRequest {
  name: string;
  description?: string | undefined;
  recipients: string[];
  nsfw?: boolean | undefined;
}

export interface GroupsCreateResponse {
  data?: GroupsCreateResponseData | undefined;
  error?: AppError | undefined;
}

export interface GroupsCreateResponseData {
  message: string;
}

export interface GroupsListRequest {
  pagination?: PaginationRequest | undefined;
}

export interface GroupsListResponse {
  data?: GroupsListResponseData | undefined;
  error?: AppError | undefined;
}

export interface GroupsListResponseData {
  groups: GroupsListItem[];
  pagination?: PaginationResponse | undefined;
}

export interface GroupsListItem {
  /** channel id */
  id: string;
  group?: ChannelGroup | undefined;
  createdAt: string;
}

function createBaseGroupsCreateRequest(): GroupsCreateRequest {
  return { name: "", description: undefined, recipients: [], nsfw: undefined };
}

export const GroupsCreateRequest: MessageFns<GroupsCreateRequest> = {
  encode(message: GroupsCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(18).string(message.description);
    }
    for (const v of message.recipients) {
      writer.uint32(26).string(v!);
    }
    if (message.nsfw !== undefined) {
      writer.uint32(32).bool(message.nsfw);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.recipients.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.nsfw = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsCreateRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      recipients: globalThis.Array.isArray(object?.recipients)
        ? object.recipients.map((e: any) => globalThis.String(e))
        : [],
      nsfw: isSet(object.nsfw) ? globalThis.Boolean(object.nsfw) : undefined,
    };
  },

  toJSON(message: GroupsCreateRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.recipients?.length) {
      obj.recipients = message.recipients;
    }
    if (message.nsfw !== undefined) {
      obj.nsfw = message.nsfw;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsCreateRequest>, I>>(base?: I): GroupsCreateRequest {
    return GroupsCreateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsCreateRequest>, I>>(object: I): GroupsCreateRequest {
    const message = createBaseGroupsCreateRequest();
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.recipients = object.recipients?.map((e) => e) || [];
    message.nsfw = object.nsfw ?? undefined;
    return message;
  },
};

function createBaseGroupsCreateResponse(): GroupsCreateResponse {
  return { data: undefined, error: undefined };
}

export const GroupsCreateResponse: MessageFns<GroupsCreateResponse> = {
  encode(message: GroupsCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      GroupsCreateResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = GroupsCreateResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsCreateResponse {
    return {
      data: isSet(object.data) ? GroupsCreateResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: GroupsCreateResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = GroupsCreateResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsCreateResponse>, I>>(base?: I): GroupsCreateResponse {
    return GroupsCreateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsCreateResponse>, I>>(object: I): GroupsCreateResponse {
    const message = createBaseGroupsCreateResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? GroupsCreateResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGroupsCreateResponseData(): GroupsCreateResponseData {
  return { message: "" };
}

export const GroupsCreateResponseData: MessageFns<GroupsCreateResponseData> = {
  encode(message: GroupsCreateResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsCreateResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsCreateResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsCreateResponseData {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: GroupsCreateResponseData): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsCreateResponseData>, I>>(base?: I): GroupsCreateResponseData {
    return GroupsCreateResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsCreateResponseData>, I>>(object: I): GroupsCreateResponseData {
    const message = createBaseGroupsCreateResponseData();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseGroupsListRequest(): GroupsListRequest {
  return { pagination: undefined };
}

export const GroupsListRequest: MessageFns<GroupsListRequest> = {
  encode(message: GroupsListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pagination !== undefined) {
      PaginationRequest.encode(message.pagination, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pagination = PaginationRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsListRequest {
    return { pagination: isSet(object.pagination) ? PaginationRequest.fromJSON(object.pagination) : undefined };
  },

  toJSON(message: GroupsListRequest): unknown {
    const obj: any = {};
    if (message.pagination !== undefined) {
      obj.pagination = PaginationRequest.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsListRequest>, I>>(base?: I): GroupsListRequest {
    return GroupsListRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsListRequest>, I>>(object: I): GroupsListRequest {
    const message = createBaseGroupsListRequest();
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginationRequest.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseGroupsListResponse(): GroupsListResponse {
  return { data: undefined, error: undefined };
}

export const GroupsListResponse: MessageFns<GroupsListResponse> = {
  encode(message: GroupsListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      GroupsListResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = GroupsListResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsListResponse {
    return {
      data: isSet(object.data) ? GroupsListResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: GroupsListResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = GroupsListResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsListResponse>, I>>(base?: I): GroupsListResponse {
    return GroupsListResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsListResponse>, I>>(object: I): GroupsListResponse {
    const message = createBaseGroupsListResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? GroupsListResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGroupsListResponseData(): GroupsListResponseData {
  return { groups: [], pagination: undefined };
}

export const GroupsListResponseData: MessageFns<GroupsListResponseData> = {
  encode(message: GroupsListResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.groups) {
      GroupsListItem.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pagination !== undefined) {
      PaginationResponse.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsListResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsListResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.groups.push(GroupsListItem.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = PaginationResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsListResponseData {
    return {
      groups: globalThis.Array.isArray(object?.groups) ? object.groups.map((e: any) => GroupsListItem.fromJSON(e)) : [],
      pagination: isSet(object.pagination) ? PaginationResponse.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: GroupsListResponseData): unknown {
    const obj: any = {};
    if (message.groups?.length) {
      obj.groups = message.groups.map((e) => GroupsListItem.toJSON(e));
    }
    if (message.pagination !== undefined) {
      obj.pagination = PaginationResponse.toJSON(message.pagination);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsListResponseData>, I>>(base?: I): GroupsListResponseData {
    return GroupsListResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsListResponseData>, I>>(object: I): GroupsListResponseData {
    const message = createBaseGroupsListResponseData();
    message.groups = object.groups?.map((e) => GroupsListItem.fromPartial(e)) || [];
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? PaginationResponse.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseGroupsListItem(): GroupsListItem {
  return { id: "", group: undefined, createdAt: "0" };
}

export const GroupsListItem: MessageFns<GroupsListItem> = {
  encode(message: GroupsListItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.group !== undefined) {
      ChannelGroup.encode(message.group, writer.uint32(18).fork()).join();
    }
    if (message.createdAt !== "0") {
      writer.uint32(24).int64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GroupsListItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGroupsListItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.group = ChannelGroup.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GroupsListItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      group: isSet(object.group) ? ChannelGroup.fromJSON(object.group) : undefined,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
    };
  },

  toJSON(message: GroupsListItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.group !== undefined) {
      obj.group = ChannelGroup.toJSON(message.group);
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GroupsListItem>, I>>(base?: I): GroupsListItem {
    return GroupsListItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GroupsListItem>, I>>(object: I): GroupsListItem {
    const message = createBaseGroupsListItem();
    message.id = object.id ?? "";
    message.group = (object.group !== undefined && object.group !== null)
      ? ChannelGroup.fromPartial(object.group)
      : undefined;
    message.createdAt = object.createdAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
