// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/main.proto

/* eslint-disable */
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { UsersCreateRequest, UsersCreateResponse, UsersLoginRequest, UsersLoginResponse } from "./users.js";

export const protobufPackage = "service.v1";

export type ChatyServiceService = typeof ChatyServiceService;
export const ChatyServiceService = {
  usersCreate: {
    path: "/service.v1.ChatyService/UsersCreate",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UsersCreateRequest): Buffer => Buffer.from(UsersCreateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UsersCreateRequest => UsersCreateRequest.decode(value),
    responseSerialize: (value: UsersCreateResponse): Buffer => Buffer.from(UsersCreateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UsersCreateResponse => UsersCreateResponse.decode(value),
  },
  usersLogin: {
    path: "/service.v1.ChatyService/UsersLogin",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UsersLoginRequest): Buffer => Buffer.from(UsersLoginRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UsersLoginRequest => UsersLoginRequest.decode(value),
    responseSerialize: (value: UsersLoginResponse): Buffer => Buffer.from(UsersLoginResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UsersLoginResponse => UsersLoginResponse.decode(value),
  },
} as const;

export interface ChatyServiceServer extends UntypedServiceImplementation {
  usersCreate: handleUnaryCall<UsersCreateRequest, UsersCreateResponse>;
  usersLogin: handleUnaryCall<UsersLoginRequest, UsersLoginResponse>;
}

export interface ChatyServiceClient extends Client {
  usersCreate(
    request: UsersCreateRequest,
    callback: (error: ServiceError | null, response: UsersCreateResponse) => void,
  ): ClientUnaryCall;
  usersCreate(
    request: UsersCreateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UsersCreateResponse) => void,
  ): ClientUnaryCall;
  usersCreate(
    request: UsersCreateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UsersCreateResponse) => void,
  ): ClientUnaryCall;
  usersLogin(
    request: UsersLoginRequest,
    callback: (error: ServiceError | null, response: UsersLoginResponse) => void,
  ): ClientUnaryCall;
  usersLogin(
    request: UsersLoginRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UsersLoginResponse) => void,
  ): ClientUnaryCall;
  usersLogin(
    request: UsersLoginRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UsersLoginResponse) => void,
  ): ClientUnaryCall;
}

export const ChatyServiceClient = makeGenericClientConstructor(
  ChatyServiceService,
  "service.v1.ChatyService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ChatyServiceClient;
  service: typeof ChatyServiceService;
  serviceName: string;
};
