// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { AppError } from "../../shared/v1/error.js";
import { Message } from "./messages_db.js";
import { ServerMember } from "./server_members_db.js";
import { APIUser } from "./users.js";

export const protobufPackage = "service.v1";

/** Message sort direction */
export enum MessageSort {
  MESSAGE_SORT_UNSPECIFIED = 0,
  MESSAGE_SORT_LATEST = 1,
  MESSAGE_SORT_OLDEST = 2,
  MESSAGE_SORT_RELEVANCE = 3,
  UNRECOGNIZED = -1,
}

export function messageSortFromJSON(object: any): MessageSort {
  switch (object) {
    case 0:
    case "MESSAGE_SORT_UNSPECIFIED":
      return MessageSort.MESSAGE_SORT_UNSPECIFIED;
    case 1:
    case "MESSAGE_SORT_LATEST":
      return MessageSort.MESSAGE_SORT_LATEST;
    case 2:
    case "MESSAGE_SORT_OLDEST":
      return MessageSort.MESSAGE_SORT_OLDEST;
    case 3:
    case "MESSAGE_SORT_RELEVANCE":
      return MessageSort.MESSAGE_SORT_RELEVANCE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageSort.UNRECOGNIZED;
  }
}

export function messageSortToJSON(object: MessageSort): string {
  switch (object) {
    case MessageSort.MESSAGE_SORT_UNSPECIFIED:
      return "MESSAGE_SORT_UNSPECIFIED";
    case MessageSort.MESSAGE_SORT_LATEST:
      return "MESSAGE_SORT_LATEST";
    case MessageSort.MESSAGE_SORT_OLDEST:
      return "MESSAGE_SORT_OLDEST";
    case MessageSort.MESSAGE_SORT_RELEVANCE:
      return "MESSAGE_SORT_RELEVANCE";
    case MessageSort.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** What this message should reply to and how */
export interface ReplyIntent {
  /** Message Id */
  id: string;
  /** Whether this reply should mention the message's author */
  mention: boolean;
  /**
   * Whether to error if the referenced message doesn't exist.
   * Otherwise, send a message without this reply. Default is true.
   */
  failIfNotExists: boolean;
}

/** Options for querying messages */
export interface MessagesGetRequest {
  /**
   * Maximum number of messages to fetch
   * For fetching nearby messages, this is `(limit + 2)`
   */
  limit?:
    | number
    | undefined;
  /** Message id before which messages should be fetched */
  before?:
    | string
    | undefined;
  /** Message id after which messages should be fetched */
  after?:
    | string
    | undefined;
  /** Message sort direction */
  sort?:
    | MessageSort
    | undefined;
  /**
   * Message id to search around
   * Specifying 'nearby' ignores 'before', 'after' and 'sort'.
   * It will also take half of limit rounded as the limits to each side.
   * It also fetches the message ID specified.
   */
  nearby?: string | undefined;
}

export interface MessagesGetResponse {
  data?: MessagesGetResponseData | undefined;
  error?: AppError | undefined;
}

export interface MessagesGetResponseData {
  messages: Message[];
  users: APIUser[];
  members: ServerMember[];
}

function createBaseReplyIntent(): ReplyIntent {
  return { id: "", mention: false, failIfNotExists: false };
}

export const ReplyIntent: MessageFns<ReplyIntent> = {
  encode(message: ReplyIntent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.mention !== false) {
      writer.uint32(16).bool(message.mention);
    }
    if (message.failIfNotExists !== false) {
      writer.uint32(24).bool(message.failIfNotExists);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReplyIntent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReplyIntent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.mention = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.failIfNotExists = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReplyIntent {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      mention: isSet(object.mention) ? globalThis.Boolean(object.mention) : false,
      failIfNotExists: isSet(object.failIfNotExists) ? globalThis.Boolean(object.failIfNotExists) : false,
    };
  },

  toJSON(message: ReplyIntent): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.mention !== false) {
      obj.mention = message.mention;
    }
    if (message.failIfNotExists !== false) {
      obj.failIfNotExists = message.failIfNotExists;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReplyIntent>, I>>(base?: I): ReplyIntent {
    return ReplyIntent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReplyIntent>, I>>(object: I): ReplyIntent {
    const message = createBaseReplyIntent();
    message.id = object.id ?? "";
    message.mention = object.mention ?? false;
    message.failIfNotExists = object.failIfNotExists ?? false;
    return message;
  },
};

function createBaseMessagesGetRequest(): MessagesGetRequest {
  return { limit: undefined, before: undefined, after: undefined, sort: undefined, nearby: undefined };
}

export const MessagesGetRequest: MessageFns<MessagesGetRequest> = {
  encode(message: MessagesGetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.limit !== undefined) {
      writer.uint32(8).int64(message.limit);
    }
    if (message.before !== undefined) {
      writer.uint32(18).string(message.before);
    }
    if (message.after !== undefined) {
      writer.uint32(26).string(message.after);
    }
    if (message.sort !== undefined) {
      writer.uint32(32).int32(message.sort);
    }
    if (message.nearby !== undefined) {
      writer.uint32(42).string(message.nearby);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessagesGetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessagesGetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.limit = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.before = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.after = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.sort = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nearby = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessagesGetRequest {
    return {
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : undefined,
      before: isSet(object.before) ? globalThis.String(object.before) : undefined,
      after: isSet(object.after) ? globalThis.String(object.after) : undefined,
      sort: isSet(object.sort) ? messageSortFromJSON(object.sort) : undefined,
      nearby: isSet(object.nearby) ? globalThis.String(object.nearby) : undefined,
    };
  },

  toJSON(message: MessagesGetRequest): unknown {
    const obj: any = {};
    if (message.limit !== undefined) {
      obj.limit = Math.round(message.limit);
    }
    if (message.before !== undefined) {
      obj.before = message.before;
    }
    if (message.after !== undefined) {
      obj.after = message.after;
    }
    if (message.sort !== undefined) {
      obj.sort = messageSortToJSON(message.sort);
    }
    if (message.nearby !== undefined) {
      obj.nearby = message.nearby;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessagesGetRequest>, I>>(base?: I): MessagesGetRequest {
    return MessagesGetRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessagesGetRequest>, I>>(object: I): MessagesGetRequest {
    const message = createBaseMessagesGetRequest();
    message.limit = object.limit ?? undefined;
    message.before = object.before ?? undefined;
    message.after = object.after ?? undefined;
    message.sort = object.sort ?? undefined;
    message.nearby = object.nearby ?? undefined;
    return message;
  },
};

function createBaseMessagesGetResponse(): MessagesGetResponse {
  return { data: undefined, error: undefined };
}

export const MessagesGetResponse: MessageFns<MessagesGetResponse> = {
  encode(message: MessagesGetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== undefined) {
      MessagesGetResponseData.encode(message.data, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      AppError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessagesGetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessagesGetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = MessagesGetResponseData.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = AppError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessagesGetResponse {
    return {
      data: isSet(object.data) ? MessagesGetResponseData.fromJSON(object.data) : undefined,
      error: isSet(object.error) ? AppError.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: MessagesGetResponse): unknown {
    const obj: any = {};
    if (message.data !== undefined) {
      obj.data = MessagesGetResponseData.toJSON(message.data);
    }
    if (message.error !== undefined) {
      obj.error = AppError.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessagesGetResponse>, I>>(base?: I): MessagesGetResponse {
    return MessagesGetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessagesGetResponse>, I>>(object: I): MessagesGetResponse {
    const message = createBaseMessagesGetResponse();
    message.data = (object.data !== undefined && object.data !== null)
      ? MessagesGetResponseData.fromPartial(object.data)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? AppError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseMessagesGetResponseData(): MessagesGetResponseData {
  return { messages: [], users: [], members: [] };
}

export const MessagesGetResponseData: MessageFns<MessagesGetResponseData> = {
  encode(message: MessagesGetResponseData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.messages) {
      Message.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.users) {
      APIUser.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.members) {
      ServerMember.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessagesGetResponseData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessagesGetResponseData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.messages.push(Message.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.users.push(APIUser.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.members.push(ServerMember.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessagesGetResponseData {
    return {
      messages: globalThis.Array.isArray(object?.messages) ? object.messages.map((e: any) => Message.fromJSON(e)) : [],
      users: globalThis.Array.isArray(object?.users) ? object.users.map((e: any) => APIUser.fromJSON(e)) : [],
      members: globalThis.Array.isArray(object?.members)
        ? object.members.map((e: any) => ServerMember.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MessagesGetResponseData): unknown {
    const obj: any = {};
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => Message.toJSON(e));
    }
    if (message.users?.length) {
      obj.users = message.users.map((e) => APIUser.toJSON(e));
    }
    if (message.members?.length) {
      obj.members = message.members.map((e) => ServerMember.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessagesGetResponseData>, I>>(base?: I): MessagesGetResponseData {
    return MessagesGetResponseData.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessagesGetResponseData>, I>>(object: I): MessagesGetResponseData {
    const message = createBaseMessagesGetResponseData();
    message.messages = object.messages?.map((e) => Message.fromPartial(e)) || [];
    message.users = object.users?.map((e) => APIUser.fromPartial(e)) || [];
    message.members = object.members?.map((e) => ServerMember.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
