// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/roles_db.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "service.v1";

/**
 * ===========================================
 * OVERRIDE FIELD TYPE (permissions)
 * ===========================================
 */
export interface OverrideField {
  /** Allowed permissions */
  allow: string;
  /** Denied permissions */
  deny: string;
}

export interface Role {
  /** Role name */
  name: string;
  /** Permissions available to this role */
  permissions?:
    | OverrideField
    | undefined;
  /** Colour used for this role (any valid CSS colour, optional) */
  colour?:
    | string
    | undefined;
  /** Whether this role should be shown separately on the member sidebar */
  hoist: boolean;
  /** Ranking of this role */
  rank: string;
}

function createBaseOverrideField(): OverrideField {
  return { allow: "0", deny: "0" };
}

export const OverrideField: MessageFns<OverrideField> = {
  encode(message: OverrideField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allow !== "0") {
      writer.uint32(8).int64(message.allow);
    }
    if (message.deny !== "0") {
      writer.uint32(16).int64(message.deny);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OverrideField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOverrideField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.allow = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.deny = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OverrideField {
    return {
      allow: isSet(object.allow) ? globalThis.String(object.allow) : "0",
      deny: isSet(object.deny) ? globalThis.String(object.deny) : "0",
    };
  },

  toJSON(message: OverrideField): unknown {
    const obj: any = {};
    if (message.allow !== "0") {
      obj.allow = message.allow;
    }
    if (message.deny !== "0") {
      obj.deny = message.deny;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OverrideField>, I>>(base?: I): OverrideField {
    return OverrideField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OverrideField>, I>>(object: I): OverrideField {
    const message = createBaseOverrideField();
    message.allow = object.allow ?? "0";
    message.deny = object.deny ?? "0";
    return message;
  },
};

function createBaseRole(): Role {
  return { name: "", permissions: undefined, colour: undefined, hoist: false, rank: "0" };
}

export const Role: MessageFns<Role> = {
  encode(message: Role, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.permissions !== undefined) {
      OverrideField.encode(message.permissions, writer.uint32(18).fork()).join();
    }
    if (message.colour !== undefined) {
      writer.uint32(26).string(message.colour);
    }
    if (message.hoist !== false) {
      writer.uint32(32).bool(message.hoist);
    }
    if (message.rank !== "0") {
      writer.uint32(40).int64(message.rank);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Role {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRole();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.permissions = OverrideField.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.colour = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hoist = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.rank = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Role {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      permissions: isSet(object.permissions) ? OverrideField.fromJSON(object.permissions) : undefined,
      colour: isSet(object.colour) ? globalThis.String(object.colour) : undefined,
      hoist: isSet(object.hoist) ? globalThis.Boolean(object.hoist) : false,
      rank: isSet(object.rank) ? globalThis.String(object.rank) : "0",
    };
  },

  toJSON(message: Role): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.permissions !== undefined) {
      obj.permissions = OverrideField.toJSON(message.permissions);
    }
    if (message.colour !== undefined) {
      obj.colour = message.colour;
    }
    if (message.hoist !== false) {
      obj.hoist = message.hoist;
    }
    if (message.rank !== "0") {
      obj.rank = message.rank;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Role>, I>>(base?: I): Role {
    return Role.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Role>, I>>(object: I): Role {
    const message = createBaseRole();
    message.name = object.name ?? "";
    message.permissions = (object.permissions !== undefined && object.permissions !== null)
      ? OverrideField.fromPartial(object.permissions)
      : undefined;
    message.colour = object.colour ?? undefined;
    message.hoist = object.hoist ?? false;
    message.rank = object.rank ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
