// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/servers_db.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { File } from "../../shared/v1/files.js";
import { Role } from "./roles_db.js";

export const protobufPackage = "service.v1";

export interface Server {
  id: string;
  ownerId: string;
  name: string;
  /** Description for the server */
  description?:
    | string
    | undefined;
  /** Default set of server and channel permissions */
  defaultPermissions: string;
  /** Icon attachment */
  icon?:
    | File
    | undefined;
  /** Banner attachment */
  banner?:
    | File
    | undefined;
  /** Bitfield of server flags */
  flags?:
    | number
    | undefined;
  /** Whether this server is flagged as not safe for work */
  nsfw: boolean;
  /** Whether to enable analytics */
  analytics: boolean;
  /** Whether this server should be publicly discoverable */
  discoverable: boolean;
  /** Roles for this server */
  roles: { [key: string]: Role };
  /** Categories for this server */
  categories: Category[];
  /** Configuration for sending system event messages */
  systemMessages?: ServerSystemMessagesChannels | undefined;
  stats?:
    | ServerStats
    | undefined;
  /** Channels within this server */
  channels: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Server_RolesEntry {
  key: string;
  value?: Role | undefined;
}

export interface Category {
  /** Unique ID for this category (1-32 chars) */
  id: string;
  /** Title for this category (1-32 chars) */
  title: string;
  /** Channels in this category */
  channels: string[];
}

export interface ServerSystemMessagesChannels {
  /** ID of channel to send user join messages in (optional) */
  userJoined?:
    | string
    | undefined;
  /** ID of channel to send user left messages in (optional) */
  userLeft?:
    | string
    | undefined;
  /** ID of channel to send user kicked messages in (optional) */
  userKicked?:
    | string
    | undefined;
  /** ID of channel to send user banned messages in (optional) */
  userBanned?: string | undefined;
}

export interface ServerStats {
  membersCount: number;
  channelsCount: number;
}

function createBaseServer(): Server {
  return {
    id: "",
    ownerId: "",
    name: "",
    description: undefined,
    defaultPermissions: "0",
    icon: undefined,
    banner: undefined,
    flags: undefined,
    nsfw: false,
    analytics: false,
    discoverable: false,
    roles: {},
    categories: [],
    systemMessages: undefined,
    stats: undefined,
    channels: [],
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Server: MessageFns<Server> = {
  encode(message: Server, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.ownerId !== "") {
      writer.uint32(18).string(message.ownerId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(34).string(message.description);
    }
    if (message.defaultPermissions !== "0") {
      writer.uint32(40).int64(message.defaultPermissions);
    }
    if (message.icon !== undefined) {
      File.encode(message.icon, writer.uint32(50).fork()).join();
    }
    if (message.banner !== undefined) {
      File.encode(message.banner, writer.uint32(58).fork()).join();
    }
    if (message.flags !== undefined) {
      writer.uint32(64).int32(message.flags);
    }
    if (message.nsfw !== false) {
      writer.uint32(72).bool(message.nsfw);
    }
    if (message.analytics !== false) {
      writer.uint32(80).bool(message.analytics);
    }
    if (message.discoverable !== false) {
      writer.uint32(88).bool(message.discoverable);
    }
    Object.entries(message.roles).forEach(([key, value]) => {
      Server_RolesEntry.encode({ key: key as any, value }, writer.uint32(98).fork()).join();
    });
    for (const v of message.categories) {
      Category.encode(v!, writer.uint32(106).fork()).join();
    }
    if (message.systemMessages !== undefined) {
      ServerSystemMessagesChannels.encode(message.systemMessages, writer.uint32(114).fork()).join();
    }
    if (message.stats !== undefined) {
      ServerStats.encode(message.stats, writer.uint32(122).fork()).join();
    }
    for (const v of message.channels) {
      writer.uint32(130).string(v!);
    }
    if (message.createdAt !== "0") {
      writer.uint32(136).int64(message.createdAt);
    }
    if (message.updatedAt !== "0") {
      writer.uint32(144).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Server {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.defaultPermissions = reader.int64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.icon = File.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.banner = File.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.flags = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.nsfw = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.analytics = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.discoverable = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          const entry12 = Server_RolesEntry.decode(reader, reader.uint32());
          if (entry12.value !== undefined) {
            message.roles[entry12.key] = entry12.value;
          }
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.categories.push(Category.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.systemMessages = ServerSystemMessagesChannels.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.stats = ServerStats.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.channels.push(reader.string());
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Server {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      ownerId: isSet(object.ownerId) ? globalThis.String(object.ownerId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      defaultPermissions: isSet(object.defaultPermissions) ? globalThis.String(object.defaultPermissions) : "0",
      icon: isSet(object.icon) ? File.fromJSON(object.icon) : undefined,
      banner: isSet(object.banner) ? File.fromJSON(object.banner) : undefined,
      flags: isSet(object.flags) ? globalThis.Number(object.flags) : undefined,
      nsfw: isSet(object.nsfw) ? globalThis.Boolean(object.nsfw) : false,
      analytics: isSet(object.analytics) ? globalThis.Boolean(object.analytics) : false,
      discoverable: isSet(object.discoverable) ? globalThis.Boolean(object.discoverable) : false,
      roles: isObject(object.roles)
        ? Object.entries(object.roles).reduce<{ [key: string]: Role }>((acc, [key, value]) => {
          acc[key] = Role.fromJSON(value);
          return acc;
        }, {})
        : {},
      categories: globalThis.Array.isArray(object?.categories)
        ? object.categories.map((e: any) => Category.fromJSON(e))
        : [],
      systemMessages: isSet(object.systemMessages)
        ? ServerSystemMessagesChannels.fromJSON(object.systemMessages)
        : undefined,
      stats: isSet(object.stats) ? ServerStats.fromJSON(object.stats) : undefined,
      channels: globalThis.Array.isArray(object?.channels) ? object.channels.map((e: any) => globalThis.String(e)) : [],
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "0",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "0",
    };
  },

  toJSON(message: Server): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.ownerId !== "") {
      obj.ownerId = message.ownerId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.defaultPermissions !== "0") {
      obj.defaultPermissions = message.defaultPermissions;
    }
    if (message.icon !== undefined) {
      obj.icon = File.toJSON(message.icon);
    }
    if (message.banner !== undefined) {
      obj.banner = File.toJSON(message.banner);
    }
    if (message.flags !== undefined) {
      obj.flags = Math.round(message.flags);
    }
    if (message.nsfw !== false) {
      obj.nsfw = message.nsfw;
    }
    if (message.analytics !== false) {
      obj.analytics = message.analytics;
    }
    if (message.discoverable !== false) {
      obj.discoverable = message.discoverable;
    }
    if (message.roles) {
      const entries = Object.entries(message.roles);
      if (entries.length > 0) {
        obj.roles = {};
        entries.forEach(([k, v]) => {
          obj.roles[k] = Role.toJSON(v);
        });
      }
    }
    if (message.categories?.length) {
      obj.categories = message.categories.map((e) => Category.toJSON(e));
    }
    if (message.systemMessages !== undefined) {
      obj.systemMessages = ServerSystemMessagesChannels.toJSON(message.systemMessages);
    }
    if (message.stats !== undefined) {
      obj.stats = ServerStats.toJSON(message.stats);
    }
    if (message.channels?.length) {
      obj.channels = message.channels;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Server>, I>>(base?: I): Server {
    return Server.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Server>, I>>(object: I): Server {
    const message = createBaseServer();
    message.id = object.id ?? "";
    message.ownerId = object.ownerId ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? undefined;
    message.defaultPermissions = object.defaultPermissions ?? "0";
    message.icon = (object.icon !== undefined && object.icon !== null) ? File.fromPartial(object.icon) : undefined;
    message.banner = (object.banner !== undefined && object.banner !== null)
      ? File.fromPartial(object.banner)
      : undefined;
    message.flags = object.flags ?? undefined;
    message.nsfw = object.nsfw ?? false;
    message.analytics = object.analytics ?? false;
    message.discoverable = object.discoverable ?? false;
    message.roles = Object.entries(object.roles ?? {}).reduce<{ [key: string]: Role }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = Role.fromPartial(value);
      }
      return acc;
    }, {});
    message.categories = object.categories?.map((e) => Category.fromPartial(e)) || [];
    message.systemMessages = (object.systemMessages !== undefined && object.systemMessages !== null)
      ? ServerSystemMessagesChannels.fromPartial(object.systemMessages)
      : undefined;
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? ServerStats.fromPartial(object.stats)
      : undefined;
    message.channels = object.channels?.map((e) => e) || [];
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

function createBaseServer_RolesEntry(): Server_RolesEntry {
  return { key: "", value: undefined };
}

export const Server_RolesEntry: MessageFns<Server_RolesEntry> = {
  encode(message: Server_RolesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Role.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Server_RolesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServer_RolesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Role.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Server_RolesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Role.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: Server_RolesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Role.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Server_RolesEntry>, I>>(base?: I): Server_RolesEntry {
    return Server_RolesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Server_RolesEntry>, I>>(object: I): Server_RolesEntry {
    const message = createBaseServer_RolesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Role.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseCategory(): Category {
  return { id: "", title: "", channels: [] };
}

export const Category: MessageFns<Category> = {
  encode(message: Category, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    for (const v of message.channels) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Category {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCategory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.channels.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Category {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      channels: globalThis.Array.isArray(object?.channels) ? object.channels.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Category): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.channels?.length) {
      obj.channels = message.channels;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Category>, I>>(base?: I): Category {
    return Category.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Category>, I>>(object: I): Category {
    const message = createBaseCategory();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.channels = object.channels?.map((e) => e) || [];
    return message;
  },
};

function createBaseServerSystemMessagesChannels(): ServerSystemMessagesChannels {
  return { userJoined: undefined, userLeft: undefined, userKicked: undefined, userBanned: undefined };
}

export const ServerSystemMessagesChannels: MessageFns<ServerSystemMessagesChannels> = {
  encode(message: ServerSystemMessagesChannels, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userJoined !== undefined) {
      writer.uint32(10).string(message.userJoined);
    }
    if (message.userLeft !== undefined) {
      writer.uint32(18).string(message.userLeft);
    }
    if (message.userKicked !== undefined) {
      writer.uint32(26).string(message.userKicked);
    }
    if (message.userBanned !== undefined) {
      writer.uint32(34).string(message.userBanned);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerSystemMessagesChannels {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerSystemMessagesChannels();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userJoined = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userLeft = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userKicked = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userBanned = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerSystemMessagesChannels {
    return {
      userJoined: isSet(object.userJoined) ? globalThis.String(object.userJoined) : undefined,
      userLeft: isSet(object.userLeft) ? globalThis.String(object.userLeft) : undefined,
      userKicked: isSet(object.userKicked) ? globalThis.String(object.userKicked) : undefined,
      userBanned: isSet(object.userBanned) ? globalThis.String(object.userBanned) : undefined,
    };
  },

  toJSON(message: ServerSystemMessagesChannels): unknown {
    const obj: any = {};
    if (message.userJoined !== undefined) {
      obj.userJoined = message.userJoined;
    }
    if (message.userLeft !== undefined) {
      obj.userLeft = message.userLeft;
    }
    if (message.userKicked !== undefined) {
      obj.userKicked = message.userKicked;
    }
    if (message.userBanned !== undefined) {
      obj.userBanned = message.userBanned;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerSystemMessagesChannels>, I>>(base?: I): ServerSystemMessagesChannels {
    return ServerSystemMessagesChannels.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerSystemMessagesChannels>, I>>(object: I): ServerSystemMessagesChannels {
    const message = createBaseServerSystemMessagesChannels();
    message.userJoined = object.userJoined ?? undefined;
    message.userLeft = object.userLeft ?? undefined;
    message.userKicked = object.userKicked ?? undefined;
    message.userBanned = object.userBanned ?? undefined;
    return message;
  },
};

function createBaseServerStats(): ServerStats {
  return { membersCount: 0, channelsCount: 0 };
}

export const ServerStats: MessageFns<ServerStats> = {
  encode(message: ServerStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.membersCount !== 0) {
      writer.uint32(8).int32(message.membersCount);
    }
    if (message.channelsCount !== 0) {
      writer.uint32(16).int32(message.channelsCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.membersCount = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.channelsCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerStats {
    return {
      membersCount: isSet(object.membersCount) ? globalThis.Number(object.membersCount) : 0,
      channelsCount: isSet(object.channelsCount) ? globalThis.Number(object.channelsCount) : 0,
    };
  },

  toJSON(message: ServerStats): unknown {
    const obj: any = {};
    if (message.membersCount !== 0) {
      obj.membersCount = Math.round(message.membersCount);
    }
    if (message.channelsCount !== 0) {
      obj.channelsCount = Math.round(message.channelsCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerStats>, I>>(base?: I): ServerStats {
    return ServerStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerStats>, I>>(object: I): ServerStats {
    const message = createBaseServerStats();
    message.membersCount = object.membersCount ?? 0;
    message.channelsCount = object.channelsCount ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
