// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: shared/v1/files.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "shared.v1";

/**
 * ===========================================
 * FILE TYPE
 * ===========================================
 */
export interface File {
  /** Unique Id */
  id: string;
  /** ID of user who uploaded this file */
  uploaderId: string;
  /** Tag / bucket this file was uploaded to */
  bucket: string;
  /** Original filename */
  filename: string;
  /** Raw content type of this file */
  contentType: string;
  /** Size of this file (in bytes) */
  size: number;
  /** Hash of this file */
  hash: string;
  /** When this file was uploaded */
  uploadedAt: number;
  /** Whether this file was deleted */
  deleted?:
    | boolean
    | undefined;
  /** Whether this file was reported */
  reported?: boolean | undefined;
  metadata?:
    | FileMetadata
    | undefined;
  /** Whether this file should have a spoiler */
  isSpoiler?: boolean | undefined;
}

export interface FileMetadata {
  file?: FileMetadataFile | undefined;
  text?: FileMetadataText | undefined;
  image?: FileMetadataImage | undefined;
  video?: FileMetadataVideo | undefined;
  audio?: FileMetadataAudio | undefined;
}

export interface FileMetadataFile {
  fileType: string;
}

export interface FileMetadataText {
  textLength: number;
}

export interface FileMetadataImage {
  width: number;
  height: number;
}

export interface FileMetadataVideo {
  width: number;
  height: number;
}

export interface FileMetadataAudio {
  audioDuration: number;
}

function createBaseFile(): File {
  return {
    id: "",
    uploaderId: "",
    bucket: "",
    filename: "",
    contentType: "",
    size: 0,
    hash: "",
    uploadedAt: 0,
    deleted: undefined,
    reported: undefined,
    metadata: undefined,
    isSpoiler: undefined,
  };
}

export const File: MessageFns<File> = {
  encode(message: File, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.uploaderId !== "") {
      writer.uint32(18).string(message.uploaderId);
    }
    if (message.bucket !== "") {
      writer.uint32(26).string(message.bucket);
    }
    if (message.filename !== "") {
      writer.uint32(34).string(message.filename);
    }
    if (message.contentType !== "") {
      writer.uint32(42).string(message.contentType);
    }
    if (message.size !== 0) {
      writer.uint32(48).int64(message.size);
    }
    if (message.hash !== "") {
      writer.uint32(58).string(message.hash);
    }
    if (message.uploadedAt !== 0) {
      writer.uint32(64).int64(message.uploadedAt);
    }
    if (message.deleted !== undefined) {
      writer.uint32(72).bool(message.deleted);
    }
    if (message.reported !== undefined) {
      writer.uint32(80).bool(message.reported);
    }
    if (message.metadata !== undefined) {
      FileMetadata.encode(message.metadata, writer.uint32(90).fork()).join();
    }
    if (message.isSpoiler !== undefined) {
      writer.uint32(96).bool(message.isSpoiler);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): File {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.uploaderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bucket = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.size = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.uploadedAt = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.deleted = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.reported = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.metadata = FileMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.isSpoiler = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): File {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      uploaderId: isSet(object.uploaderId) ? globalThis.String(object.uploaderId) : "",
      bucket: isSet(object.bucket) ? globalThis.String(object.bucket) : "",
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      contentType: isSet(object.contentType) ? globalThis.String(object.contentType) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      uploadedAt: isSet(object.uploadedAt) ? globalThis.Number(object.uploadedAt) : 0,
      deleted: isSet(object.deleted) ? globalThis.Boolean(object.deleted) : undefined,
      reported: isSet(object.reported) ? globalThis.Boolean(object.reported) : undefined,
      metadata: isSet(object.metadata) ? FileMetadata.fromJSON(object.metadata) : undefined,
      isSpoiler: isSet(object.isSpoiler) ? globalThis.Boolean(object.isSpoiler) : undefined,
    };
  },

  toJSON(message: File): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.uploaderId !== "") {
      obj.uploaderId = message.uploaderId;
    }
    if (message.bucket !== "") {
      obj.bucket = message.bucket;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.contentType !== "") {
      obj.contentType = message.contentType;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.uploadedAt !== 0) {
      obj.uploadedAt = Math.round(message.uploadedAt);
    }
    if (message.deleted !== undefined) {
      obj.deleted = message.deleted;
    }
    if (message.reported !== undefined) {
      obj.reported = message.reported;
    }
    if (message.metadata !== undefined) {
      obj.metadata = FileMetadata.toJSON(message.metadata);
    }
    if (message.isSpoiler !== undefined) {
      obj.isSpoiler = message.isSpoiler;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<File>, I>>(base?: I): File {
    return File.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<File>, I>>(object: I): File {
    const message = createBaseFile();
    message.id = object.id ?? "";
    message.uploaderId = object.uploaderId ?? "";
    message.bucket = object.bucket ?? "";
    message.filename = object.filename ?? "";
    message.contentType = object.contentType ?? "";
    message.size = object.size ?? 0;
    message.hash = object.hash ?? "";
    message.uploadedAt = object.uploadedAt ?? 0;
    message.deleted = object.deleted ?? undefined;
    message.reported = object.reported ?? undefined;
    message.metadata = (object.metadata !== undefined && object.metadata !== null)
      ? FileMetadata.fromPartial(object.metadata)
      : undefined;
    message.isSpoiler = object.isSpoiler ?? undefined;
    return message;
  },
};

function createBaseFileMetadata(): FileMetadata {
  return { file: undefined, text: undefined, image: undefined, video: undefined, audio: undefined };
}

export const FileMetadata: MessageFns<FileMetadata> = {
  encode(message: FileMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.file !== undefined) {
      FileMetadataFile.encode(message.file, writer.uint32(10).fork()).join();
    }
    if (message.text !== undefined) {
      FileMetadataText.encode(message.text, writer.uint32(18).fork()).join();
    }
    if (message.image !== undefined) {
      FileMetadataImage.encode(message.image, writer.uint32(26).fork()).join();
    }
    if (message.video !== undefined) {
      FileMetadataVideo.encode(message.video, writer.uint32(34).fork()).join();
    }
    if (message.audio !== undefined) {
      FileMetadataAudio.encode(message.audio, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file = FileMetadataFile.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = FileMetadataText.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.image = FileMetadataImage.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.video = FileMetadataVideo.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.audio = FileMetadataAudio.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadata {
    return {
      file: isSet(object.file) ? FileMetadataFile.fromJSON(object.file) : undefined,
      text: isSet(object.text) ? FileMetadataText.fromJSON(object.text) : undefined,
      image: isSet(object.image) ? FileMetadataImage.fromJSON(object.image) : undefined,
      video: isSet(object.video) ? FileMetadataVideo.fromJSON(object.video) : undefined,
      audio: isSet(object.audio) ? FileMetadataAudio.fromJSON(object.audio) : undefined,
    };
  },

  toJSON(message: FileMetadata): unknown {
    const obj: any = {};
    if (message.file !== undefined) {
      obj.file = FileMetadataFile.toJSON(message.file);
    }
    if (message.text !== undefined) {
      obj.text = FileMetadataText.toJSON(message.text);
    }
    if (message.image !== undefined) {
      obj.image = FileMetadataImage.toJSON(message.image);
    }
    if (message.video !== undefined) {
      obj.video = FileMetadataVideo.toJSON(message.video);
    }
    if (message.audio !== undefined) {
      obj.audio = FileMetadataAudio.toJSON(message.audio);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadata>, I>>(base?: I): FileMetadata {
    return FileMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadata>, I>>(object: I): FileMetadata {
    const message = createBaseFileMetadata();
    message.file = (object.file !== undefined && object.file !== null)
      ? FileMetadataFile.fromPartial(object.file)
      : undefined;
    message.text = (object.text !== undefined && object.text !== null)
      ? FileMetadataText.fromPartial(object.text)
      : undefined;
    message.image = (object.image !== undefined && object.image !== null)
      ? FileMetadataImage.fromPartial(object.image)
      : undefined;
    message.video = (object.video !== undefined && object.video !== null)
      ? FileMetadataVideo.fromPartial(object.video)
      : undefined;
    message.audio = (object.audio !== undefined && object.audio !== null)
      ? FileMetadataAudio.fromPartial(object.audio)
      : undefined;
    return message;
  },
};

function createBaseFileMetadataFile(): FileMetadataFile {
  return { fileType: "" };
}

export const FileMetadataFile: MessageFns<FileMetadataFile> = {
  encode(message: FileMetadataFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fileType !== "") {
      writer.uint32(10).string(message.fileType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadataFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadataFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fileType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadataFile {
    return { fileType: isSet(object.fileType) ? globalThis.String(object.fileType) : "" };
  },

  toJSON(message: FileMetadataFile): unknown {
    const obj: any = {};
    if (message.fileType !== "") {
      obj.fileType = message.fileType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadataFile>, I>>(base?: I): FileMetadataFile {
    return FileMetadataFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadataFile>, I>>(object: I): FileMetadataFile {
    const message = createBaseFileMetadataFile();
    message.fileType = object.fileType ?? "";
    return message;
  },
};

function createBaseFileMetadataText(): FileMetadataText {
  return { textLength: 0 };
}

export const FileMetadataText: MessageFns<FileMetadataText> = {
  encode(message: FileMetadataText, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.textLength !== 0) {
      writer.uint32(8).int64(message.textLength);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadataText {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadataText();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.textLength = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadataText {
    return { textLength: isSet(object.textLength) ? globalThis.Number(object.textLength) : 0 };
  },

  toJSON(message: FileMetadataText): unknown {
    const obj: any = {};
    if (message.textLength !== 0) {
      obj.textLength = Math.round(message.textLength);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadataText>, I>>(base?: I): FileMetadataText {
    return FileMetadataText.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadataText>, I>>(object: I): FileMetadataText {
    const message = createBaseFileMetadataText();
    message.textLength = object.textLength ?? 0;
    return message;
  },
};

function createBaseFileMetadataImage(): FileMetadataImage {
  return { width: 0, height: 0 };
}

export const FileMetadataImage: MessageFns<FileMetadataImage> = {
  encode(message: FileMetadataImage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.width !== 0) {
      writer.uint32(8).int64(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(16).int64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadataImage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadataImage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.width = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.height = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadataImage {
    return {
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
    };
  },

  toJSON(message: FileMetadataImage): unknown {
    const obj: any = {};
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadataImage>, I>>(base?: I): FileMetadataImage {
    return FileMetadataImage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadataImage>, I>>(object: I): FileMetadataImage {
    const message = createBaseFileMetadataImage();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseFileMetadataVideo(): FileMetadataVideo {
  return { width: 0, height: 0 };
}

export const FileMetadataVideo: MessageFns<FileMetadataVideo> = {
  encode(message: FileMetadataVideo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.width !== 0) {
      writer.uint32(8).int64(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(16).int64(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadataVideo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadataVideo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.width = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.height = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadataVideo {
    return {
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
    };
  },

  toJSON(message: FileMetadataVideo): unknown {
    const obj: any = {};
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadataVideo>, I>>(base?: I): FileMetadataVideo {
    return FileMetadataVideo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadataVideo>, I>>(object: I): FileMetadataVideo {
    const message = createBaseFileMetadataVideo();
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseFileMetadataAudio(): FileMetadataAudio {
  return { audioDuration: 0 };
}

export const FileMetadataAudio: MessageFns<FileMetadataAudio> = {
  encode(message: FileMetadataAudio, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.audioDuration !== 0) {
      writer.uint32(8).int64(message.audioDuration);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FileMetadataAudio {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFileMetadataAudio();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.audioDuration = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FileMetadataAudio {
    return { audioDuration: isSet(object.audioDuration) ? globalThis.Number(object.audioDuration) : 0 };
  },

  toJSON(message: FileMetadataAudio): unknown {
    const obj: any = {};
    if (message.audioDuration !== 0) {
      obj.audioDuration = Math.round(message.audioDuration);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FileMetadataAudio>, I>>(base?: I): FileMetadataAudio {
    return FileMetadataAudio.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FileMetadataAudio>, I>>(object: I): FileMetadataAudio {
    const message = createBaseFileMetadataAudio();
    message.audioDuration = object.audioDuration ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
