// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: shared/v1/files.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "shared.v1";

/**
 * ===========================================
 * FILE TYPE
 * ===========================================
 */
export interface File {
  /** Unique Id */
  id: string;
  /** ID of user who uploaded this file */
  uploaderId: string;
  /** Tag / bucket this file was uploaded to */
  bucket: string;
  /** Original filename */
  filename: string;
  /** Raw content type of this file */
  contentType: string;
  /** Size of this file (in bytes) */
  size: string;
  /** Hash of this file */
  hash: string;
  /** When this file was uploaded */
  uploadedAt: string;
  /** Whether this file was deleted */
  deleted?:
    | boolean
    | undefined;
  /** Whether this file was reported */
  reported?: boolean | undefined;
}

function createBaseFile(): File {
  return {
    id: "",
    uploaderId: "",
    bucket: "",
    filename: "",
    contentType: "",
    size: "0",
    hash: "",
    uploadedAt: "0",
    deleted: undefined,
    reported: undefined,
  };
}

export const File: MessageFns<File> = {
  encode(message: File, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.uploaderId !== "") {
      writer.uint32(18).string(message.uploaderId);
    }
    if (message.bucket !== "") {
      writer.uint32(26).string(message.bucket);
    }
    if (message.filename !== "") {
      writer.uint32(34).string(message.filename);
    }
    if (message.contentType !== "") {
      writer.uint32(42).string(message.contentType);
    }
    if (message.size !== "0") {
      writer.uint32(48).int64(message.size);
    }
    if (message.hash !== "") {
      writer.uint32(58).string(message.hash);
    }
    if (message.uploadedAt !== "0") {
      writer.uint32(64).int64(message.uploadedAt);
    }
    if (message.deleted !== undefined) {
      writer.uint32(72).bool(message.deleted);
    }
    if (message.reported !== undefined) {
      writer.uint32(80).bool(message.reported);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): File {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.uploaderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.bucket = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.size = reader.int64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.uploadedAt = reader.int64().toString();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.deleted = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.reported = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): File {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      uploaderId: isSet(object.uploaderId) ? globalThis.String(object.uploaderId) : "",
      bucket: isSet(object.bucket) ? globalThis.String(object.bucket) : "",
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      contentType: isSet(object.contentType) ? globalThis.String(object.contentType) : "",
      size: isSet(object.size) ? globalThis.String(object.size) : "0",
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
      uploadedAt: isSet(object.uploadedAt) ? globalThis.String(object.uploadedAt) : "0",
      deleted: isSet(object.deleted) ? globalThis.Boolean(object.deleted) : undefined,
      reported: isSet(object.reported) ? globalThis.Boolean(object.reported) : undefined,
    };
  },

  toJSON(message: File): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.uploaderId !== "") {
      obj.uploaderId = message.uploaderId;
    }
    if (message.bucket !== "") {
      obj.bucket = message.bucket;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.contentType !== "") {
      obj.contentType = message.contentType;
    }
    if (message.size !== "0") {
      obj.size = message.size;
    }
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    if (message.uploadedAt !== "0") {
      obj.uploadedAt = message.uploadedAt;
    }
    if (message.deleted !== undefined) {
      obj.deleted = message.deleted;
    }
    if (message.reported !== undefined) {
      obj.reported = message.reported;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<File>, I>>(base?: I): File {
    return File.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<File>, I>>(object: I): File {
    const message = createBaseFile();
    message.id = object.id ?? "";
    message.uploaderId = object.uploaderId ?? "";
    message.bucket = object.bucket ?? "";
    message.filename = object.filename ?? "";
    message.contentType = object.contentType ?? "";
    message.size = object.size ?? "0";
    message.hash = object.hash ?? "";
    message.uploadedAt = object.uploadedAt ?? "0";
    message.deleted = object.deleted ?? undefined;
    message.reported = object.reported ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
