// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/channels.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Channel } from "./channels_db_pb.js";
import { file_service_v1_channels_db } from "./channels_db_pb.js";
import type { AppError } from "../../shared/v1/error_pb.js";
import { file_shared_v1_error } from "../../shared/v1/error_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/channels.proto.
 */
export const file_service_v1_channels: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL3YxL2NoYW5uZWxzLnByb3RvEgpzZXJ2aWNlLnYxIiAKEkNoYW5uZWxzR2V0UmVxdWVzdBIKCgJpZBgBIAEoCSJsChNDaGFubmVsc0dldFJlc3BvbnNlEiMKBGRhdGEYASABKAsyEy5zZXJ2aWNlLnYxLkNoYW5uZWxIABIkCgVlcnJvchgCIAEoCzITLnNoYXJlZC52MS5BcHBFcnJvckgAQgoKCHJlc3BvbnNlYgZwcm90bzM", [file_service_v1_channels_db, file_shared_v1_error]);

/**
 * @generated from message service.v1.ChannelsGetRequest
 */
export type ChannelsGetRequest = Message<"service.v1.ChannelsGetRequest"> & {
  /**
   * channel id
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message service.v1.ChannelsGetRequest.
 * Use `create(ChannelsGetRequestSchema)` to create a new message.
 */
export const ChannelsGetRequestSchema: GenMessage<ChannelsGetRequest> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 0);

/**
 * @generated from message service.v1.ChannelsGetResponse
 */
export type ChannelsGetResponse = Message<"service.v1.ChannelsGetResponse"> & {
  /**
   * @generated from oneof service.v1.ChannelsGetResponse.response
   */
  response: {
    /**
     * @generated from field: service.v1.Channel data = 1;
     */
    value: Channel;
    case: "data";
  } | {
    /**
     * @generated from field: shared.v1.AppError error = 2;
     */
    value: AppError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message service.v1.ChannelsGetResponse.
 * Use `create(ChannelsGetResponseSchema)` to create a new message.
 */
export const ChannelsGetResponseSchema: GenMessage<ChannelsGetResponse> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 1);

