// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/channels_db.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { File } from "../../shared/v1/files_pb.js";
import { file_shared_v1_files } from "../../shared/v1/files_pb.js";
import type { Timestamp } from "../../shared/v1/time_pb.js";
import { file_shared_v1_time } from "../../shared/v1/time_pb.js";
import type { OverrideField } from "./roles_db_pb.js";
import { file_service_v1_roles_db } from "./roles_db_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/channels_db.proto.
 */
export const file_service_v1_channels_db: GenFile = /*@__PURE__*/
  fileDesc("ChxzZXJ2aWNlL3YxL2NoYW5uZWxzX2RiLnByb3RvEgpzZXJ2aWNlLnYxIvQBCgxDaGFubmVsR3JvdXASDwoHdXNlcl9pZBgBIAEoCRIMCgRuYW1lGAIgASgJEhgKC2Rlc2NyaXB0aW9uGAMgASgJSACIAQESEgoKcmVjaXBpZW50cxgEIAMoCRIdCgRpY29uGAUgASgLMg8uc2hhcmVkLnYxLkZpbGUSHAoPbGFzdF9tZXNzYWdlX2lkGAYgASgJSAGIAQESGAoLcGVybWlzc2lvbnMYByABKANIAogBARIMCgRuc2Z3GAggASgIQg4KDF9kZXNjcmlwdGlvbkISChBfbGFzdF9tZXNzYWdlX2lkQg4KDF9wZXJtaXNzaW9ucyInChRDaGFubmVsU2F2ZWRNZXNzYWdlcxIPCgd1c2VyX2lkGAEgASgJIooDCgtDaGFubmVsVGV4dBIRCglzZXJ2ZXJfaWQYASABKAkSDAoEbmFtZRgCIAEoCRIYCgtkZXNjcmlwdGlvbhgDIAEoCUgAiAEBEh0KBGljb24YBCABKAsyDy5zaGFyZWQudjEuRmlsZRIcCg9sYXN0X21lc3NhZ2VfaWQYBSABKAlIAYgBARI2ChNkZWZhdWx0X3Blcm1pc3Npb25zGAYgASgLMhkuc2VydmljZS52MS5PdmVycmlkZUZpZWxkEkYKEHJvbGVfcGVybWlzc2lvbnMYByADKAsyLC5zZXJ2aWNlLnYxLkNoYW5uZWxUZXh0LlJvbGVQZXJtaXNzaW9uc0VudHJ5EgwKBG5zZncYCCABKAgaUQoUUm9sZVBlcm1pc3Npb25zRW50cnkSCwoDa2V5GAEgASgJEigKBXZhbHVlGAIgASgLMhkuc2VydmljZS52MS5PdmVycmlkZUZpZWxkOgI4AUIOCgxfZGVzY3JpcHRpb25CEgoQX2xhc3RfbWVzc2FnZV9pZCJsChRDaGFubmVsRGlyZWN0TWVzc2FnZRIOCgZhY3RpdmUYASABKAgSEgoKcmVjaXBpZW50cxgCIAMoCRIcCg9sYXN0X21lc3NhZ2VfaWQYAyABKAlIAIgBAUISChBfbGFzdF9tZXNzYWdlX2lkIvwCCgdDaGFubmVsEgoKAmlkGAEgASgJEhQKDGNoYW5uZWxfdHlwZRgCIAEoCRIxCgVzYXZlZBgDIAEoCzIgLnNlcnZpY2UudjEuQ2hhbm5lbFNhdmVkTWVzc2FnZXNIABIyCgZkaXJlY3QYBCABKAsyIC5zZXJ2aWNlLnYxLkNoYW5uZWxEaXJlY3RNZXNzYWdlSAASKQoFZ3JvdXAYBSABKAsyGC5zZXJ2aWNlLnYxLkNoYW5uZWxHcm91cEgAEicKBHRleHQYBiABKAsyFy5zZXJ2aWNlLnYxLkNoYW5uZWxUZXh0SAASHAoPdm9pY2VfbWF4X3VzZXJzGAcgASgFSAGIAQESKAoKY3JlYXRlZF9hdBgIIAEoCzIULnNoYXJlZC52MS5UaW1lc3RhbXASKAoKdXBkYXRlZF9hdBgJIAEoCzIULnNoYXJlZC52MS5UaW1lc3RhbXBCDgoMY2hhbm5lbF9kYXRhQhIKEF92b2ljZV9tYXhfdXNlcnNiBnByb3RvMw", [file_shared_v1_files, file_shared_v1_time, file_service_v1_roles_db]);

/**
 * Group channel type
 *
 * @generated from message service.v1.ChannelGroup
 */
export type ChannelGroup = Message<"service.v1.ChannelGroup"> & {
  /**
   * User id of the owner of the group
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Display name of the channel
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Channel description
   *
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * Array of user ids participating in channel
   *
   * @generated from field: repeated string recipients = 4;
   */
  recipients: string[];

  /**
   * Custom icon attachment
   *
   * @generated from field: shared.v1.File icon = 5;
   */
  icon?: File;

  /**
   * Id of the last message sent in this channel
   *
   * @generated from field: optional string last_message_id = 6;
   */
  lastMessageId?: string;

  /**
   * Permissions assigned to members of this group (does not apply to owner)
   *
   * @generated from field: optional int64 permissions = 7;
   */
  permissions?: bigint;

  /**
   * Whether this group is marked as not safe for work
   *
   * @generated from field: bool nsfw = 8;
   */
  nsfw: boolean;
};

/**
 * Describes the message service.v1.ChannelGroup.
 * Use `create(ChannelGroupSchema)` to create a new message.
 */
export const ChannelGroupSchema: GenMessage<ChannelGroup> = /*@__PURE__*/
  messageDesc(file_service_v1_channels_db, 0);

/**
 * Saved messages channel type
 *
 * @generated from message service.v1.ChannelSavedMessages
 */
export type ChannelSavedMessages = Message<"service.v1.ChannelSavedMessages"> & {
  /**
   * Id of the user this channel belongs to
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message service.v1.ChannelSavedMessages.
 * Use `create(ChannelSavedMessagesSchema)` to create a new message.
 */
export const ChannelSavedMessagesSchema: GenMessage<ChannelSavedMessages> = /*@__PURE__*/
  messageDesc(file_service_v1_channels_db, 1);

/**
 * Text channel type
 *
 * @generated from message service.v1.ChannelText
 */
export type ChannelText = Message<"service.v1.ChannelText"> & {
  /**
   * Id of the server this channel belongs to
   *
   * @generated from field: string server_id = 1;
   */
  serverId: string;

  /**
   * Display name of the channel
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Channel description (optional)
   *
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * Custom icon attachment (optional)
   *
   * @generated from field: shared.v1.File icon = 4;
   */
  icon?: File;

  /**
   * Id of the last message sent in this channel (optional)
   *
   * @generated from field: optional string last_message_id = 5;
   */
  lastMessageId?: string;

  /**
   * Default permissions assigned to users in this channel (optional)
   *
   * @generated from field: service.v1.OverrideField default_permissions = 6;
   */
  defaultPermissions?: OverrideField;

  /**
   * Map of role_id -> permissions
   *
   * @generated from field: map<string, service.v1.OverrideField> role_permissions = 7;
   */
  rolePermissions: { [key: string]: OverrideField };

  /**
   * Whether this channel is marked as not safe for work
   *
   * @generated from field: bool nsfw = 8;
   */
  nsfw: boolean;
};

/**
 * Describes the message service.v1.ChannelText.
 * Use `create(ChannelTextSchema)` to create a new message.
 */
export const ChannelTextSchema: GenMessage<ChannelText> = /*@__PURE__*/
  messageDesc(file_service_v1_channels_db, 2);

/**
 * Direct message channel type
 *
 * @generated from message service.v1.ChannelDirectMessage
 */
export type ChannelDirectMessage = Message<"service.v1.ChannelDirectMessage"> & {
  /**
   * Whether this direct message channel is currently open on both sides
   *
   * @generated from field: bool active = 1;
   */
  active: boolean;

  /**
   * 2-tuple of user ids participating in direct message
   *
   * @generated from field: repeated string recipients = 2;
   */
  recipients: string[];

  /**
   * Id of the last message sent in this channel
   *
   * @generated from field: optional string last_message_id = 3;
   */
  lastMessageId?: string;
};

/**
 * Describes the message service.v1.ChannelDirectMessage.
 * Use `create(ChannelDirectMessageSchema)` to create a new message.
 */
export const ChannelDirectMessageSchema: GenMessage<ChannelDirectMessage> = /*@__PURE__*/
  messageDesc(file_service_v1_channels_db, 3);

/**
 * ===========================================
 * MAIN CHANNELS TABLE
 * ===========================================
 *
 * @generated from message service.v1.Channel
 */
export type Channel = Message<"service.v1.Channel"> & {
  /**
   * ULID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 'saved_messages', 'direct_message', 'group', 'text_channel'
   *
   * @generated from field: string channel_type = 2;
   */
  channelType: string;

  /**
   * Channel types (oneof - only one is set based on channel_type)
   *
   * @generated from oneof service.v1.Channel.channel_data
   */
  channelData: {
    /**
     * @generated from field: service.v1.ChannelSavedMessages saved = 3;
     */
    value: ChannelSavedMessages;
    case: "saved";
  } | {
    /**
     * @generated from field: service.v1.ChannelDirectMessage direct = 4;
     */
    value: ChannelDirectMessage;
    case: "direct";
  } | {
    /**
     * @generated from field: service.v1.ChannelGroup group = 5;
     */
    value: ChannelGroup;
    case: "group";
  } | {
    /**
     * @generated from field: service.v1.ChannelText text = 6;
     */
    value: ChannelText;
    case: "text";
  } | { case: undefined; value?: undefined };

  /**
   * Maximum users allowed in voice channel
   *
   * @generated from field: optional int32 voice_max_users = 7;
   */
  voiceMaxUsers?: number;

  /**
   * @generated from field: shared.v1.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: shared.v1.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message service.v1.Channel.
 * Use `create(ChannelSchema)` to create a new message.
 */
export const ChannelSchema: GenMessage<Channel> = /*@__PURE__*/
  messageDesc(file_service_v1_channels_db, 4);

