// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/channels.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Channel } from "./channels_db_pb.js";
import { file_service_v1_channels_db } from "./channels_db_pb.js";
import type { AppError } from "../../shared/v1/error_pb.js";
import { file_shared_v1_error } from "../../shared/v1/error_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/channels.proto.
 */
export const file_service_v1_channels: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL3YxL2NoYW5uZWxzLnByb3RvEgpzZXJ2aWNlLnYxInAKDUNoYW5uZWxVbnJlYWQSKwoCaWQYASABKAsyHy5zZXJ2aWNlLnYxLkNoYW5uZWxDb21wb3NpdGVLZXkSFAoHbGFzdF9pZBgCIAEoCUgAiAEBEhAKCG1lbnRpb25zGAMgAygJQgoKCF9sYXN0X2lkIjQKE0NoYW5uZWxDb21wb3NpdGVLZXkSDwoHY2hhbm5lbBgBIAEoCRIMCgR1c2VyGAIgASgJIiAKEkNoYW5uZWxzR2V0UmVxdWVzdBIKCgJpZBgBIAEoCSJsChNDaGFubmVsc0dldFJlc3BvbnNlEiMKBGRhdGEYASABKAsyEy5zZXJ2aWNlLnYxLkNoYW5uZWxIABIkCgVlcnJvchgCIAEoCzITLnNoYXJlZC52MS5BcHBFcnJvckgAQgoKCHJlc3BvbnNlIrMBChVDaGFubmVsc0NyZWF0ZVJlcXVlc3QSFAoMY2hhbm5lbF90eXBlGAEgASgJEgwKBG5hbWUYAiABKAkSGAoLZGVzY3JpcHRpb24YAyABKAlIAIgBARIRCgRuc2Z3GAQgASgISAGIAQESHAoPdm9pY2VfbWF4X3VzZXJzGAUgASgNSAKIAQFCDgoMX2Rlc2NyaXB0aW9uQgcKBV9uc2Z3QhIKEF92b2ljZV9tYXhfdXNlcnMiGAoWQ2hhbm5lbHNDcmVhdGVSZXNwb25zZWIGcHJvdG8z", [file_service_v1_channels_db, file_shared_v1_error]);

/**
 * Channel Unread
 *
 * @generated from message service.v1.ChannelUnread
 */
export type ChannelUnread = Message<"service.v1.ChannelUnread"> & {
  /**
   * @generated from field: service.v1.ChannelCompositeKey id = 1;
   */
  id?: ChannelCompositeKey;

  /**
   * Id of the last message read in this channel by a user
   *
   * @generated from field: optional string last_id = 2;
   */
  lastId?: string;

  /**
   * Array of message ids that mention the user
   *
   * @generated from field: repeated string mentions = 3;
   */
  mentions: string[];
};

/**
 * Describes the message service.v1.ChannelUnread.
 * Use `create(ChannelUnreadSchema)` to create a new message.
 */
export const ChannelUnreadSchema: GenMessage<ChannelUnread> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 0);

/**
 * Composite primary key consisting of channel and user id
 *
 * @generated from message service.v1.ChannelCompositeKey
 */
export type ChannelCompositeKey = Message<"service.v1.ChannelCompositeKey"> & {
  /**
   * * @description Channel Id 
   *
   * @generated from field: string channel = 1;
   */
  channel: string;

  /**
   * * @description User Id 
   *
   * @generated from field: string user = 2;
   */
  user: string;
};

/**
 * Describes the message service.v1.ChannelCompositeKey.
 * Use `create(ChannelCompositeKeySchema)` to create a new message.
 */
export const ChannelCompositeKeySchema: GenMessage<ChannelCompositeKey> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 1);

/**
 * @generated from message service.v1.ChannelsGetRequest
 */
export type ChannelsGetRequest = Message<"service.v1.ChannelsGetRequest"> & {
  /**
   * channel id
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message service.v1.ChannelsGetRequest.
 * Use `create(ChannelsGetRequestSchema)` to create a new message.
 */
export const ChannelsGetRequestSchema: GenMessage<ChannelsGetRequest> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 2);

/**
 * @generated from message service.v1.ChannelsGetResponse
 */
export type ChannelsGetResponse = Message<"service.v1.ChannelsGetResponse"> & {
  /**
   * @generated from oneof service.v1.ChannelsGetResponse.response
   */
  response: {
    /**
     * @generated from field: service.v1.Channel data = 1;
     */
    value: Channel;
    case: "data";
  } | {
    /**
     * @generated from field: shared.v1.AppError error = 2;
     */
    value: AppError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message service.v1.ChannelsGetResponse.
 * Use `create(ChannelsGetResponseSchema)` to create a new message.
 */
export const ChannelsGetResponseSchema: GenMessage<ChannelsGetResponse> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 3);

/**
 * @generated from message service.v1.ChannelsCreateRequest
 */
export type ChannelsCreateRequest = Message<"service.v1.ChannelsCreateRequest"> & {
  /**
   * Channel type (voice or text)
   *
   * @generated from field: string channel_type = 1;
   */
  channelType: string;

  /**
   * Channel name
   * Validation: length(min = 1, max = 32)
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Channel description
   * Validation: length(min = 0, max = 1024)
   *
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * Whether this channel is age restricted
   *
   * @generated from field: optional bool nsfw = 4;
   */
  nsfw?: boolean;

  /**
   * Voice Information for when this channel is also a voice channel
   *
   * @generated from field: optional uint32 voice_max_users = 5;
   */
  voiceMaxUsers?: number;
};

/**
 * Describes the message service.v1.ChannelsCreateRequest.
 * Use `create(ChannelsCreateRequestSchema)` to create a new message.
 */
export const ChannelsCreateRequestSchema: GenMessage<ChannelsCreateRequest> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 4);

/**
 * @generated from message service.v1.ChannelsCreateResponse
 */
export type ChannelsCreateResponse = Message<"service.v1.ChannelsCreateResponse"> & {
};

/**
 * Describes the message service.v1.ChannelsCreateResponse.
 * Use `create(ChannelsCreateResponseSchema)` to create a new message.
 */
export const ChannelsCreateResponseSchema: GenMessage<ChannelsCreateResponse> = /*@__PURE__*/
  messageDesc(file_service_v1_channels, 5);

