// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/main.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { UsersCreateRequestSchema, UsersCreateResponseSchema, UsersLoginRequestSchema, UsersLoginResponseSchema } from "./users_pb.js";
import { file_service_v1_users } from "./users_pb.js";

/**
 * Describes the file service/v1/main.proto.
 */
export const file_service_v1_main: GenFile = /*@__PURE__*/
  fileDesc("ChVzZXJ2aWNlL3YxL21haW4ucHJvdG8SCnNlcnZpY2UudjEyqwEKDENoYXR5U2VydmljZRJOCgtVc2Vyc0NyZWF0ZRIeLnNlcnZpY2UudjEuVXNlcnNDcmVhdGVSZXF1ZXN0Gh8uc2VydmljZS52MS5Vc2Vyc0NyZWF0ZVJlc3BvbnNlEksKClVzZXJzTG9naW4SHS5zZXJ2aWNlLnYxLlVzZXJzTG9naW5SZXF1ZXN0Gh4uc2VydmljZS52MS5Vc2Vyc0xvZ2luUmVzcG9uc2ViBnByb3RvMw", [file_service_v1_users]);

/**
 * @generated from service service.v1.ChatyService
 */
export const ChatyService: GenService<{
  /**
   * @generated from rpc service.v1.ChatyService.UsersCreate
   */
  usersCreate: {
    methodKind: "unary";
    input: typeof UsersCreateRequestSchema;
    output: typeof UsersCreateResponseSchema;
  },
  /**
   * @generated from rpc service.v1.ChatyService.UsersLogin
   */
  usersLogin: {
    methodKind: "unary";
    input: typeof UsersLoginRequestSchema;
    output: typeof UsersLoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service_v1_main, 0);

