// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/messages.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "./messages_db_pb.js";
import { file_service_v1_messages_db } from "./messages_db_pb.js";
import type { ServerMember } from "./server_members_db_pb.js";
import { file_service_v1_server_members_db } from "./server_members_db_pb.js";
import type { APIUser } from "./users_pb.js";
import { file_service_v1_users } from "./users_pb.js";
import type { AppError } from "../../shared/v1/error_pb.js";
import { file_shared_v1_error } from "../../shared/v1/error_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/messages.proto.
 */
export const file_service_v1_messages: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL3YxL21lc3NhZ2VzLnByb3RvEgpzZXJ2aWNlLnYxIkYKC1JlcGx5SW50ZW50EgoKAmlkGAEgASgJEg8KB21lbnRpb24YAiABKAgSGgoSZmFpbF9pZl9ub3RfZXhpc3RzGAMgASgIItkBChJNZXNzYWdlc0dldFJlcXVlc3QSEgoKY2hhbm5lbF9pZBgBIAEoCRISCgVsaW1pdBgCIAEoA0gAiAEBEhMKBmJlZm9yZRgDIAEoCUgBiAEBEhIKBWFmdGVyGAQgASgJSAKIAQESKgoEc29ydBgFIAEoDjIXLnNlcnZpY2UudjEuTWVzc2FnZVNvcnRIA4gBARITCgZuZWFyYnkYBiABKAlIBIgBAUIICgZfbGltaXRCCQoHX2JlZm9yZUIICgZfYWZ0ZXJCBwoFX3NvcnRCCQoHX25lYXJieSJ8ChNNZXNzYWdlc0dldFJlc3BvbnNlEjMKBGRhdGEYASABKAsyIy5zZXJ2aWNlLnYxLk1lc3NhZ2VzR2V0UmVzcG9uc2VEYXRhSAASJAoFZXJyb3IYAiABKAsyEy5zaGFyZWQudjEuQXBwRXJyb3JIAEIKCghyZXNwb25zZSKPAQoXTWVzc2FnZXNHZXRSZXNwb25zZURhdGESJQoIbWVzc2FnZXMYASADKAsyEy5zZXJ2aWNlLnYxLk1lc3NhZ2USIgoFdXNlcnMYAiADKAsyEy5zZXJ2aWNlLnYxLkFQSVVzZXISKQoHbWVtYmVycxgDIAMoCzIYLnNlcnZpY2UudjEuU2VydmVyTWVtYmVyKnkKC01lc3NhZ2VTb3J0EhwKGE1FU1NBR0VfU09SVF9VTlNQRUNJRklFRBAAEhcKE01FU1NBR0VfU09SVF9MQVRFU1QQARIXChNNRVNTQUdFX1NPUlRfT0xERVNUEAISGgoWTUVTU0FHRV9TT1JUX1JFTEVWQU5DRRADYgZwcm90bzM", [file_service_v1_messages_db, file_service_v1_server_members_db, file_service_v1_users, file_shared_v1_error]);

/**
 * *  What this message should reply to and how 
 *
 * @generated from message service.v1.ReplyIntent
 */
export type ReplyIntent = Message<"service.v1.ReplyIntent"> & {
  /**
   * * Message Id 
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * * Whether this reply should mention the message's author 
   *
   * @generated from field: bool mention = 2;
   */
  mention: boolean;

  /**
   * * Whether to error if the referenced message doesn't exist.
   * Otherwise, send a message without this reply. Default is true.
   *
   * @generated from field: bool fail_if_not_exists = 3;
   */
  failIfNotExists: boolean;
};

/**
 * Describes the message service.v1.ReplyIntent.
 * Use `create(ReplyIntentSchema)` to create a new message.
 */
export const ReplyIntentSchema: GenMessage<ReplyIntent> = /*@__PURE__*/
  messageDesc(file_service_v1_messages, 0);

/**
 * Options for querying messages
 *
 * @generated from message service.v1.MessagesGetRequest
 */
export type MessagesGetRequest = Message<"service.v1.MessagesGetRequest"> & {
  /**
   * @generated from field: string channel_id = 1;
   */
  channelId: string;

  /**
   * Maximum number of messages to fetch
   * For fetching nearby messages, this is `(limit + 2)`
   *
   * @generated from field: optional int64 limit = 2;
   */
  limit?: bigint;

  /**
   * Message id before which messages should be fetched
   *
   * @generated from field: optional string before = 3;
   */
  before?: string;

  /**
   * Message id after which messages should be fetched
   *
   * @generated from field: optional string after = 4;
   */
  after?: string;

  /**
   * Message sort direction
   *
   * @generated from field: optional service.v1.MessageSort sort = 5;
   */
  sort?: MessageSort;

  /**
   * Message id to search around
   * Specifying 'nearby' ignores 'before', 'after' and 'sort'.
   * It will also take half of limit rounded as the limits to each side.
   * It also fetches the message ID specified.
   *
   * @generated from field: optional string nearby = 6;
   */
  nearby?: string;
};

/**
 * Describes the message service.v1.MessagesGetRequest.
 * Use `create(MessagesGetRequestSchema)` to create a new message.
 */
export const MessagesGetRequestSchema: GenMessage<MessagesGetRequest> = /*@__PURE__*/
  messageDesc(file_service_v1_messages, 1);

/**
 * @generated from message service.v1.MessagesGetResponse
 */
export type MessagesGetResponse = Message<"service.v1.MessagesGetResponse"> & {
  /**
   * @generated from oneof service.v1.MessagesGetResponse.response
   */
  response: {
    /**
     * @generated from field: service.v1.MessagesGetResponseData data = 1;
     */
    value: MessagesGetResponseData;
    case: "data";
  } | {
    /**
     * @generated from field: shared.v1.AppError error = 2;
     */
    value: AppError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message service.v1.MessagesGetResponse.
 * Use `create(MessagesGetResponseSchema)` to create a new message.
 */
export const MessagesGetResponseSchema: GenMessage<MessagesGetResponse> = /*@__PURE__*/
  messageDesc(file_service_v1_messages, 2);

/**
 * @generated from message service.v1.MessagesGetResponseData
 */
export type MessagesGetResponseData = Message<"service.v1.MessagesGetResponseData"> & {
  /**
   * @generated from field: repeated service.v1.Message messages = 1;
   */
  messages: Message$1[];

  /**
   * @generated from field: repeated service.v1.APIUser users = 2;
   */
  users: APIUser[];

  /**
   * @generated from field: repeated service.v1.ServerMember members = 3;
   */
  members: ServerMember[];
};

/**
 * Describes the message service.v1.MessagesGetResponseData.
 * Use `create(MessagesGetResponseDataSchema)` to create a new message.
 */
export const MessagesGetResponseDataSchema: GenMessage<MessagesGetResponseData> = /*@__PURE__*/
  messageDesc(file_service_v1_messages, 3);

/**
 * Message sort direction
 *
 * @generated from enum service.v1.MessageSort
 */
export enum MessageSort {
  /**
   * @generated from enum value: MESSAGE_SORT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_SORT_LATEST = 1;
   */
  LATEST = 1,

  /**
   * @generated from enum value: MESSAGE_SORT_OLDEST = 2;
   */
  OLDEST = 2,

  /**
   * @generated from enum value: MESSAGE_SORT_RELEVANCE = 3;
   */
  RELEVANCE = 3,
}

/**
 * Describes the enum service.v1.MessageSort.
 */
export const MessageSortSchema: GenEnum<MessageSort> = /*@__PURE__*/
  enumDesc(file_service_v1_messages, 0);

