// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/servers_db.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Role } from "./roles_db_pb.js";
import { file_service_v1_roles_db } from "./roles_db_pb.js";
import { file_shared_v1_error } from "../../shared/v1/error_pb.js";
import type { File } from "../../shared/v1/files_pb.js";
import { file_shared_v1_files } from "../../shared/v1/files_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/servers_db.proto.
 */
export const file_service_v1_servers_db: GenFile = /*@__PURE__*/
  fileDesc("ChtzZXJ2aWNlL3YxL3NlcnZlcnNfZGIucHJvdG8SCnNlcnZpY2UudjEihAUKBlNlcnZlchIKCgJpZBgBIAEoCRIQCghvd25lcl9pZBgCIAEoCRIMCgRuYW1lGAMgASgJEhgKC2Rlc2NyaXB0aW9uGAQgASgJSACIAQESGwoTZGVmYXVsdF9wZXJtaXNzaW9ucxgFIAEoAxIiCgRpY29uGAYgASgLMg8uc2hhcmVkLnYxLkZpbGVIAYgBARIkCgZiYW5uZXIYByABKAsyDy5zaGFyZWQudjEuRmlsZUgCiAEBEhIKBWZsYWdzGAggASgFSAOIAQESDAoEbnNmdxgJIAEoCBIRCglhbmFseXRpY3MYCiABKAgSFAoMZGlzY292ZXJhYmxlGAsgASgIEiwKBXJvbGVzGAwgAygLMh0uc2VydmljZS52MS5TZXJ2ZXIuUm9sZXNFbnRyeRIoCgpjYXRlZ29yaWVzGA0gAygLMhQuc2VydmljZS52MS5DYXRlZ29yeRJGCg9zeXN0ZW1fbWVzc2FnZXMYDiABKAsyKC5zZXJ2aWNlLnYxLlNlcnZlclN5c3RlbU1lc3NhZ2VzQ2hhbm5lbHNIBIgBARImCgVzdGF0cxgPIAEoCzIXLnNlcnZpY2UudjEuU2VydmVyU3RhdHMSEAoIY2hhbm5lbHMYECADKAkSEgoKY3JlYXRlZF9hdBgRIAEoAxISCgp1cGRhdGVkX2F0GBIgASgDGj4KClJvbGVzRW50cnkSCwoDa2V5GAEgASgJEh8KBXZhbHVlGAIgASgLMhAuc2VydmljZS52MS5Sb2xlOgI4AUIOCgxfZGVzY3JpcHRpb25CBwoFX2ljb25CCQoHX2Jhbm5lckIICgZfZmxhZ3NCEgoQX3N5c3RlbV9tZXNzYWdlcyI3CghDYXRlZ29yeRIKCgJpZBgBIAEoCRINCgV0aXRsZRgCIAEoCRIQCghjaGFubmVscxgDIAMoCSLCAQocU2VydmVyU3lzdGVtTWVzc2FnZXNDaGFubmVscxIYCgt1c2VyX2pvaW5lZBgBIAEoCUgAiAEBEhYKCXVzZXJfbGVmdBgCIAEoCUgBiAEBEhgKC3VzZXJfa2lja2VkGAMgASgJSAKIAQESGAoLdXNlcl9iYW5uZWQYBCABKAlIA4gBAUIOCgxfdXNlcl9qb2luZWRCDAoKX3VzZXJfbGVmdEIOCgxfdXNlcl9raWNrZWRCDgoMX3VzZXJfYmFubmVkIjwKC1NlcnZlclN0YXRzEhUKDW1lbWJlcnNfY291bnQYASABKAUSFgoOY2hhbm5lbHNfY291bnQYAiABKAViBnByb3RvMw", [file_service_v1_roles_db, file_shared_v1_error, file_shared_v1_files]);

/**
 * @generated from message service.v1.Server
 */
export type Server = Message<"service.v1.Server"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string owner_id = 2;
   */
  ownerId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Description for the server
   *
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * Default set of server and channel permissions
   *
   * @generated from field: int64 default_permissions = 5;
   */
  defaultPermissions: bigint;

  /**
   * Icon attachment
   *
   * @generated from field: optional shared.v1.File icon = 6;
   */
  icon?: File;

  /**
   * Banner attachment
   *
   * @generated from field: optional shared.v1.File banner = 7;
   */
  banner?: File;

  /**
   * Bitfield of server flags
   *
   * @generated from field: optional int32 flags = 8;
   */
  flags?: number;

  /**
   * Whether this server is flagged as not safe for work
   *
   * @generated from field: bool nsfw = 9;
   */
  nsfw: boolean;

  /**
   * Whether to enable analytics
   *
   * @generated from field: bool analytics = 10;
   */
  analytics: boolean;

  /**
   * Whether this server should be publicly discoverable
   *
   * @generated from field: bool discoverable = 11;
   */
  discoverable: boolean;

  /**
   * Roles for this server
   *
   * @generated from field: map<string, service.v1.Role> roles = 12;
   */
  roles: { [key: string]: Role };

  /**
   * Categories for this server
   *
   * @generated from field: repeated service.v1.Category categories = 13;
   */
  categories: Category[];

  /**
   * Configuration for sending system event messages
   *
   * @generated from field: optional service.v1.ServerSystemMessagesChannels system_messages = 14;
   */
  systemMessages?: ServerSystemMessagesChannels;

  /**
   * @generated from field: service.v1.ServerStats stats = 15;
   */
  stats?: ServerStats;

  /**
   * Channels within this server
   *
   * @generated from field: repeated string channels = 16;
   */
  channels: string[];

  /**
   * @generated from field: int64 created_at = 17;
   */
  createdAt: bigint;

  /**
   * @generated from field: int64 updated_at = 18;
   */
  updatedAt: bigint;
};

/**
 * Describes the message service.v1.Server.
 * Use `create(ServerSchema)` to create a new message.
 */
export const ServerSchema: GenMessage<Server> = /*@__PURE__*/
  messageDesc(file_service_v1_servers_db, 0);

/**
 * @generated from message service.v1.Category
 */
export type Category = Message<"service.v1.Category"> & {
  /**
   * Unique ID for this category (1-32 chars)
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Title for this category (1-32 chars)
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * Channels in this category
   *
   * @generated from field: repeated string channels = 3;
   */
  channels: string[];
};

/**
 * Describes the message service.v1.Category.
 * Use `create(CategorySchema)` to create a new message.
 */
export const CategorySchema: GenMessage<Category> = /*@__PURE__*/
  messageDesc(file_service_v1_servers_db, 1);

/**
 * @generated from message service.v1.ServerSystemMessagesChannels
 */
export type ServerSystemMessagesChannels = Message<"service.v1.ServerSystemMessagesChannels"> & {
  /**
   * ID of channel to send user join messages in (optional)
   *
   * @generated from field: optional string user_joined = 1;
   */
  userJoined?: string;

  /**
   * ID of channel to send user left messages in (optional)
   *
   * @generated from field: optional string user_left = 2;
   */
  userLeft?: string;

  /**
   * ID of channel to send user kicked messages in (optional)
   *
   * @generated from field: optional string user_kicked = 3;
   */
  userKicked?: string;

  /**
   * ID of channel to send user banned messages in (optional)
   *
   * @generated from field: optional string user_banned = 4;
   */
  userBanned?: string;
};

/**
 * Describes the message service.v1.ServerSystemMessagesChannels.
 * Use `create(ServerSystemMessagesChannelsSchema)` to create a new message.
 */
export const ServerSystemMessagesChannelsSchema: GenMessage<ServerSystemMessagesChannels> = /*@__PURE__*/
  messageDesc(file_service_v1_servers_db, 2);

/**
 * @generated from message service.v1.ServerStats
 */
export type ServerStats = Message<"service.v1.ServerStats"> & {
  /**
   * @generated from field: int32 members_count = 1;
   */
  membersCount: number;

  /**
   * @generated from field: int32 channels_count = 2;
   */
  channelsCount: number;
};

/**
 * Describes the message service.v1.ServerStats.
 * Use `create(ServerStatsSchema)` to create a new message.
 */
export const ServerStatsSchema: GenMessage<ServerStats> = /*@__PURE__*/
  messageDesc(file_service_v1_servers_db, 3);

