// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/servers.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { AppError } from "../../shared/v1/error_pb.js";
import { file_shared_v1_error } from "../../shared/v1/error_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/servers.proto.
 */
export const file_service_v1_servers: GenFile = /*@__PURE__*/
  fileDesc("ChhzZXJ2aWNlL3YxL3NlcnZlcnMucHJvdG8SCnNlcnZpY2UudjEiagoUU2VydmVyc0NyZWF0ZVJlcXVlc3QSDAoEbmFtZRgBIAEoCRIYCgtkZXNjcmlwdGlvbhgCIAEoCUgAiAEBEhEKBG5zZncYAyABKAhIAYgBAUIOCgxfZGVzY3JpcHRpb25CBwoFX25zZncigAEKFVNlcnZlcnNDcmVhdGVSZXNwb25zZRI1CgRkYXRhGAEgASgLMiUuc2VydmljZS52MS5TZXJ2ZXJzQ3JlYXRlUmVzcG9uc2VEYXRhSAASJAoFZXJyb3IYAiABKAsyEy5zaGFyZWQudjEuQXBwRXJyb3JIAEIKCghyZXNwb25zZSIbChlTZXJ2ZXJzQ3JlYXRlUmVzcG9uc2VEYXRhYgZwcm90bzM", [file_shared_v1_error]);

/**
 * Information about new server to create
 *
 * @generated from message service.v1.ServersCreateRequest
 */
export type ServersCreateRequest = Message<"service.v1.ServersCreateRequest"> & {
  /**
   * Server name
   * Validation: length(min = 1, max = 32)
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Server description
   * Validation: length(min = 0, max = 1024)
   *
   * @generated from field: optional string description = 2;
   */
  description?: string;

  /**
   * Whether this server is age-restricted
   *
   * @generated from field: optional bool nsfw = 3;
   */
  nsfw?: boolean;
};

/**
 * Describes the message service.v1.ServersCreateRequest.
 * Use `create(ServersCreateRequestSchema)` to create a new message.
 */
export const ServersCreateRequestSchema: GenMessage<ServersCreateRequest> = /*@__PURE__*/
  messageDesc(file_service_v1_servers, 0);

/**
 * @generated from message service.v1.ServersCreateResponse
 */
export type ServersCreateResponse = Message<"service.v1.ServersCreateResponse"> & {
  /**
   * @generated from oneof service.v1.ServersCreateResponse.response
   */
  response: {
    /**
     * @generated from field: service.v1.ServersCreateResponseData data = 1;
     */
    value: ServersCreateResponseData;
    case: "data";
  } | {
    /**
     * @generated from field: shared.v1.AppError error = 2;
     */
    value: AppError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message service.v1.ServersCreateResponse.
 * Use `create(ServersCreateResponseSchema)` to create a new message.
 */
export const ServersCreateResponseSchema: GenMessage<ServersCreateResponse> = /*@__PURE__*/
  messageDesc(file_service_v1_servers, 1);

/**
 * @generated from message service.v1.ServersCreateResponseData
 */
export type ServersCreateResponseData = Message<"service.v1.ServersCreateResponseData"> & {
};

/**
 * Describes the message service.v1.ServersCreateResponseData.
 * Use `create(ServersCreateResponseDataSchema)` to create a new message.
 */
export const ServersCreateResponseDataSchema: GenMessage<ServersCreateResponseData> = /*@__PURE__*/
  messageDesc(file_service_v1_servers, 2);

