// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/users_db.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/users_db.proto.
 */
export const file_service_v1_users_db: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL3YxL3VzZXJzX2RiLnByb3RvEgpzZXJ2aWNlLnYxIvUDCgRVc2VyEgoKAmlkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEhAKCHBhc3N3b3JkGAQgASgJEhkKDGRpc3BsYXlfbmFtZRgFIAEoCUgAiAEBEhMKBmJhZGdlcxgGIAEoBUgBiAEBEhgKC3N0YXR1c190ZXh0GAcgASgJSAKIAQESNAoPc3RhdHVzX3ByZXNlbmNlGAggASgOMhYuc2VydmljZS52MS5Vc2VyU3RhdHVzSAOIAQESHAoPcHJvZmlsZV9jb250ZW50GAkgASgJSASIAQESIgoVcHJvZmlsZV9iYWNrZ3JvdW5kX2lkGAogASgJSAWIAQESEgoKcHJpdmlsZWdlZBgLIAEoCBIcCg9zdXNwZW5kZWRfdW50aWwYDCABKANIBogBARISCgpjcmVhdGVkX2F0GA0gASgDEhIKCnVwZGF0ZWRfYXQYDiABKAMSEAoIdmVyaWZpZWQYDyABKAhCDwoNX2Rpc3BsYXlfbmFtZUIJCgdfYmFkZ2VzQg4KDF9zdGF0dXNfdGV4dEISChBfc3RhdHVzX3ByZXNlbmNlQhIKEF9wcm9maWxlX2NvbnRlbnRCGAoWX3Byb2ZpbGVfYmFja2dyb3VuZF9pZEISChBfc3VzcGVuZGVkX3VudGlsKoIBCgpVc2VyU3RhdHVzEhYKElVTRVJfU1RBVFVTX09OTElORRAAEhQKEFVTRVJfU1RBVFVTX0lETEUQARIVChFVU0VSX1NUQVRVU19GT0NVUxACEhQKEFVTRVJfU1RBVFVTX0JVU1kQAxIZChVVU0VSX1NUQVRVU19JTlZJU0lCTEUQBGIGcHJvdG8z");

/**
 * @generated from message service.v1.User
 */
export type User = Message<"service.v1.User"> & {
  /**
   * ulid
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 64 char
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * 255 char
   *
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * 64 char
   *
   * @generated from field: optional string display_name = 5;
   */
  displayName?: string;

  /**
   * @generated from field: optional int32 badges = 6;
   */
  badges?: number;

  /**
   * 510 char
   *
   * @generated from field: optional string status_text = 7;
   */
  statusText?: string;

  /**
   * 32 char
   *
   * @generated from field: optional service.v1.UserStatus status_presence = 8;
   */
  statusPresence?: UserStatus;

  /**
   * text
   *
   * @generated from field: optional string profile_content = 9;
   */
  profileContent?: string;

  /**
   * ulid (26 chars) Reference to files collection
   *
   * @generated from field: optional string profile_background_id = 10;
   */
  profileBackgroundId?: string;

  /**
   * @generated from field: bool privileged = 11;
   */
  privileged: boolean;

  /**
   * @generated from field: optional int64 suspended_until = 12;
   */
  suspendedUntil?: bigint;

  /**
   * unix timestamp miliseconds
   *
   * @generated from field: int64 created_at = 13;
   */
  createdAt: bigint;

  /**
   * unix timestamp miliseconds
   *
   * @generated from field: int64 updated_at = 14;
   */
  updatedAt: bigint;

  /**
   * @generated from field: bool verified = 15;
   */
  verified: boolean;
};

/**
 * Describes the message service.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_service_v1_users_db, 0);

/**
 * @generated from enum service.v1.UserStatus
 */
export enum UserStatus {
  /**
   * @generated from enum value: USER_STATUS_ONLINE = 0;
   */
  ONLINE = 0,

  /**
   * @generated from enum value: USER_STATUS_IDLE = 1;
   */
  IDLE = 1,

  /**
   * @generated from enum value: USER_STATUS_FOCUS = 2;
   */
  FOCUS = 2,

  /**
   * @generated from enum value: USER_STATUS_BUSY = 3;
   */
  BUSY = 3,

  /**
   * @generated from enum value: USER_STATUS_INVISIBLE = 4;
   */
  INVISIBLE = 4,
}

/**
 * Describes the enum service.v1.UserStatus.
 */
export const UserStatusSchema: GenEnum<UserStatus> = /*@__PURE__*/
  enumDesc(file_service_v1_users_db, 0);

