// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file service/v1/users_db.proto (package service.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { File } from "../../shared/v1/files_pb.js";
import { file_shared_v1_files } from "../../shared/v1/files_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/v1/users_db.proto.
 */
export const file_service_v1_users_db: GenFile = /*@__PURE__*/
  fileDesc("ChlzZXJ2aWNlL3YxL3VzZXJzX2RiLnByb3RvEgpzZXJ2aWNlLnYxItcECgRVc2VyEgoKAmlkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEhAKCHBhc3N3b3JkGAQgASgJEhkKDGRpc3BsYXlfbmFtZRgFIAEoCUgAiAEBEhMKBmJhZGdlcxgGIAEoBUgBiAEBEhgKC3N0YXR1c190ZXh0GAcgASgJSAKIAQESNAoPc3RhdHVzX3ByZXNlbmNlGAggASgOMhYuc2VydmljZS52MS5Vc2VyU3RhdHVzSAOIAQESHAoPcHJvZmlsZV9jb250ZW50GAkgASgJSASIAQESIgoVcHJvZmlsZV9iYWNrZ3JvdW5kX2lkGAogASgJSAWIAQESEgoKcHJpdmlsZWdlZBgLIAEoCBIcCg9zdXNwZW5kZWRfdW50aWwYDCABKANIBogBARISCgpjcmVhdGVkX2F0GA0gASgDEhIKCnVwZGF0ZWRfYXQYDiABKAMSEAoIdmVyaWZpZWQYDyABKAgSJAoGYXZhdGFyGBAgASgLMg8uc2hhcmVkLnYxLkZpbGVIB4gBARIvCglyZWxhdGlvbnMYESADKAsyHC5zZXJ2aWNlLnYxLlVzZXJSZWxhdGlvbnNoaXBCDwoNX2Rpc3BsYXlfbmFtZUIJCgdfYmFkZ2VzQg4KDF9zdGF0dXNfdGV4dEISChBfc3RhdHVzX3ByZXNlbmNlQhIKEF9wcm9maWxlX2NvbnRlbnRCGAoWX3Byb2ZpbGVfYmFja2dyb3VuZF9pZEISChBfc3VzcGVuZGVkX3VudGlsQgkKB19hdmF0YXIiUgoQVXNlclJlbGF0aW9uc2hpcBIKCgJpZBgBIAEoCRIyCgZzdGF0dXMYAiABKA4yIi5zZXJ2aWNlLnYxLlVzZXJSZWxhdGlvbnNoaXBTdGF0dXMqggEKClVzZXJTdGF0dXMSFgoSVVNFUl9TVEFUVVNfT05MSU5FEAASFAoQVVNFUl9TVEFUVVNfSURMRRABEhUKEVVTRVJfU1RBVFVTX0ZPQ1VTEAISFAoQVVNFUl9TVEFUVVNfQlVTWRADEhkKFVVTRVJfU1RBVFVTX0lOVklTSUJMRRAEKqMCChZVc2VyUmVsYXRpb25zaGlwU3RhdHVzEiEKHVVTRVJfUkVMQVRJT05TSElQX1NUQVRVU19OT05FEAASIQodVVNFUl9SRUxBVElPTlNISVBfU1RBVFVTX1VTRVIQARIjCh9VU0VSX1JFTEFUSU9OU0hJUF9TVEFUVVNfRlJJRU5EEAISJQohVVNFUl9SRUxBVElPTlNISVBfU1RBVFVTX09VVEdPSU5HEAMSJQohVVNFUl9SRUxBVElPTlNISVBfU1RBVFVTX0lOQ09NSU5HEAQSJAogVVNFUl9SRUxBVElPTlNISVBfU1RBVFVTX0JMT0NLRUQQBRIqCiZVU0VSX1JFTEFUSU9OU0hJUF9TVEFUVVNfQkxPQ0tFRF9PVEhFUhAGYgZwcm90bzM", [file_shared_v1_files]);

/**
 * @generated from message service.v1.User
 */
export type User = Message<"service.v1.User"> & {
  /**
   * ulid
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 64 char
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * 255 char
   *
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * 64 char
   *
   * @generated from field: optional string display_name = 5;
   */
  displayName?: string;

  /**
   * @generated from field: optional int32 badges = 6;
   */
  badges?: number;

  /**
   * 510 char
   *
   * @generated from field: optional string status_text = 7;
   */
  statusText?: string;

  /**
   * 32 char
   *
   * @generated from field: optional service.v1.UserStatus status_presence = 8;
   */
  statusPresence?: UserStatus;

  /**
   * text
   *
   * @generated from field: optional string profile_content = 9;
   */
  profileContent?: string;

  /**
   * ulid (26 chars) Reference to files collection
   *
   * @generated from field: optional string profile_background_id = 10;
   */
  profileBackgroundId?: string;

  /**
   * @generated from field: bool privileged = 11;
   */
  privileged: boolean;

  /**
   * @generated from field: optional int64 suspended_until = 12;
   */
  suspendedUntil?: bigint;

  /**
   * unix timestamp miliseconds
   *
   * @generated from field: int64 created_at = 13;
   */
  createdAt: bigint;

  /**
   * unix timestamp miliseconds
   *
   * @generated from field: int64 updated_at = 14;
   */
  updatedAt: bigint;

  /**
   * @generated from field: bool verified = 15;
   */
  verified: boolean;

  /**
   * @generated from field: optional shared.v1.File avatar = 16;
   */
  avatar?: File;

  /**
   * @generated from field: repeated service.v1.UserRelationship relations = 17;
   */
  relations: UserRelationship[];
};

/**
 * Describes the message service.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_service_v1_users_db, 0);

/**
 * @generated from message service.v1.UserRelationship
 */
export type UserRelationship = Message<"service.v1.UserRelationship"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: service.v1.UserRelationshipStatus status = 2;
   */
  status: UserRelationshipStatus;
};

/**
 * Describes the message service.v1.UserRelationship.
 * Use `create(UserRelationshipSchema)` to create a new message.
 */
export const UserRelationshipSchema: GenMessage<UserRelationship> = /*@__PURE__*/
  messageDesc(file_service_v1_users_db, 1);

/**
 * @generated from enum service.v1.UserStatus
 */
export enum UserStatus {
  /**
   * @generated from enum value: USER_STATUS_ONLINE = 0;
   */
  ONLINE = 0,

  /**
   * @generated from enum value: USER_STATUS_IDLE = 1;
   */
  IDLE = 1,

  /**
   * @generated from enum value: USER_STATUS_FOCUS = 2;
   */
  FOCUS = 2,

  /**
   * @generated from enum value: USER_STATUS_BUSY = 3;
   */
  BUSY = 3,

  /**
   * @generated from enum value: USER_STATUS_INVISIBLE = 4;
   */
  INVISIBLE = 4,
}

/**
 * Describes the enum service.v1.UserStatus.
 */
export const UserStatusSchema: GenEnum<UserStatus> = /*@__PURE__*/
  enumDesc(file_service_v1_users_db, 0);

/**
 * @generated from enum service.v1.UserRelationshipStatus
 */
export enum UserRelationshipStatus {
  /**
   * @generated from enum value: USER_RELATIONSHIP_STATUS_NONE = 0;
   */
  NONE = 0,

  /**
   * Self
   *
   * @generated from enum value: USER_RELATIONSHIP_STATUS_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: USER_RELATIONSHIP_STATUS_FRIEND = 2;
   */
  FRIEND = 2,

  /**
   * Friend request sent
   *
   * @generated from enum value: USER_RELATIONSHIP_STATUS_OUTGOING = 3;
   */
  OUTGOING = 3,

  /**
   * Friend request received
   *
   * @generated from enum value: USER_RELATIONSHIP_STATUS_INCOMING = 4;
   */
  INCOMING = 4,

  /**
   * You blocked them
   *
   * @generated from enum value: USER_RELATIONSHIP_STATUS_BLOCKED = 5;
   */
  BLOCKED = 5,

  /**
   * They blocked you
   *
   * @generated from enum value: USER_RELATIONSHIP_STATUS_BLOCKED_OTHER = 6;
   */
  BLOCKED_OTHER = 6,
}

/**
 * Describes the enum service.v1.UserRelationshipStatus.
 */
export const UserRelationshipStatusSchema: GenEnum<UserRelationshipStatus> = /*@__PURE__*/
  enumDesc(file_service_v1_users_db, 1);

