syntax = "proto3";

package service.v1;

import "service/v1/channels_db.proto";
import "shared/v1/error.proto";

// Channel Unread
message ChannelUnread {
  ChannelCompositeKey id = 1;
  // Id of the last message read in this channel by a user
  optional string last_id = 2;
  // Array of message ids that mention the user
  repeated string mentions = 3;
}

// Composite primary key consisting of channel and user id
message ChannelCompositeKey {
  /** @description Channel Id */
  string channel = 1;
  /** @description User Id */
  string user = 2;
}

message ChannelsGetRequest {
  string id = 1; // channel id
}

message ChannelsGetResponse {
  oneof response {
    service.v1.Channel data = 1;
    shared.v1.AppError error = 2;
  }
}

message ChannelsCreateRequest {
  // Channel type (voice or text)
  string channel_type = 1;

  // Channel name
  // Validation: length(min = 1, max = 32)
  string name = 2;

  // Channel description
  // Validation: length(min = 0, max = 1024)
  optional string description = 3;

  // Whether this channel is age restricted
  optional bool nsfw = 4;

  // Voice Information for when this channel is also a voice channel
  optional uint32 voice_max_users = 5;
}

message ChannelsCreateResponse {}
