syntax = "proto3";

package service.v1;

import "service/v1/channels.proto";
import "service/v1/groups.proto";
import "service/v1/messages.proto";
import "service/v1/search.proto";
import "service/v1/users.proto";

service ChatyService {
  rpc UsersCreate(UsersCreateRequest) returns (UsersCreateResponse);
  rpc UsersLogin(UsersLoginRequest) returns (UsersLoginResponse);
  rpc UsersEmailConfirmation(UsersEmailConfirmationRequest) returns (UsersEmailConfirmationResponse);
  rpc UsersForgotPassword(UsersForgotPasswordRequest) returns (UsersForgotPasswordResponse);
  rpc UsersResetPassword(UsersResetPasswordRequest) returns (UsersResetPasswordResponse);
  rpc ChannelsGet(ChannelsGetRequest) returns (ChannelsGetResponse);
  rpc GroupsCreate(GroupsCreateRequest) returns (GroupsCreateResponse);
  rpc GroupsList(GroupsListRequest) returns (GroupsListResponse);
  rpc SearchUsernames(SearchUsernamesRequest) returns (SearchUsernamesResponse);
  rpc MessagesGet(MessagesGetRequest) returns (MessagesGetResponse);
  rpc MessagesSearch(MessagesSearchRequest) returns (MessagesSearchResponse);
}
