syntax = "proto3";

package service.v1;

import "service/v1/messages_db.proto";
import "service/v1/server_members_db.proto";
import "service/v1/users.proto";
import "shared/v1/error.proto";

/**  What this message should reply to and how */
message ReplyIntent {
  /** Message Id */
  string id = 1;
  /** Whether this reply should mention the message's author */
  bool mention = 2;
  /** Whether to error if the referenced message doesn't exist.
     Otherwise, send a message without this reply. Default is true.
  */
  bool fail_if_not_exists = 3;
}

// @description Representation of a text embed before it is sent.
message EmbedSendable {
  // icon_url field
  optional string icon_url = 1;
  // url field
  optional string url = 2;
  // title field
  optional string title = 3;
  // description field
  optional string description = 4;
  // media field
  optional string media = 5;
  // colour field
  optional string colour = 6;
}

// Data message for sending
message MessageIntent {
  // @description Unique token to prevent duplicate message sending
  optional string nonce = 1;

  // @description Message content to send
  optional string content = 2;

  // @description Attachments to include in message
  repeated string attachments = 3;

  // @description Messages to reply to
  repeated ReplyIntent replies = 4;

  // @description Embeds to include in message
  //
  // Text embed content contributes to the content length cap
  repeated EmbedSendable embeds = 5;

  // @description Masquerade to apply to this message
  optional service.v1.Masquerade masquerade = 6;

  // @description Information about how this message should be interacted with
  optional service.v1.Interactions interactions = 7;

  // Format: uint32
  // @description Bitfield of message flags
  optional uint32 flags = 8;
}

// Message sort direction
enum MessageSort {
  MESSAGE_SORT_UNSPECIFIED = 0;
  MESSAGE_SORT_LATEST = 1;
  MESSAGE_SORT_OLDEST = 2;
  MESSAGE_SORT_RELEVANCE = 3;
}

// Options for querying messages
message MessagesGetRequest {
  string channel_id = 1;
  // Maximum number of messages to fetch
  // For fetching nearby messages, this is `(limit + 2)`
  optional int64 limit = 2;

  // Message id before which messages should be fetched
  optional string before = 3;

  // Message id after which messages should be fetched
  optional string after = 4;

  // Message sort direction
  optional MessageSort sort = 5;

  // Message id to search around
  // Specifying 'nearby' ignores 'before', 'after' and 'sort'.
  // It will also take half of limit rounded as the limits to each side.
  // It also fetches the message ID specified.
  optional string nearby = 6;

  optional bool include_users = 7;
}

message MessagesGetResponse {
  oneof response {
    MessagesGetResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message MessagesGetResponseData {
  repeated service.v1.Message messages = 1;
  repeated service.v1.APIUser users = 2;
  repeated service.v1.ServerMember members = 3;
}

message MessagesSearchRequest {
  // Full-text search query
  optional string query = 1;

  // Whether to only search for pinned messages, cannot be sent with query
  optional bool pinned = 2;

  // Maximum number of messages to fetch
  optional int64 limit = 3;

  // Message id before which messages should be fetched
  optional string before = 4;

  // Message id after which messages should be fetched
  optional string after = 5;

  // Message sort direction
  // By default, it will be sorted by latest (default: RELEVANCE)
  optional MessageSort sort = 6;

  // Whether to include user (and member, if server channel) objects
  optional bool include_users = 7;
}

message MessagesSearchResponse {
  oneof response {
    MessagesSearchResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message MessagesSearchResponseData {
  repeated service.v1.Message messages = 1;
  repeated service.v1.APIUser users = 2;
  repeated service.v1.ServerMember members = 3;
}
