syntax = "proto3";

package service.v1;

import "service/v1/bots_db.proto";
import "service/v1/users_db.proto";
import "shared/v1/error.proto";
import "shared/v1/files.proto";

message APIUser {
  string id = 1; // ulid
  string username = 2; // 64 char
  string email = 3; // 255 char
  // User's relationship with another user (or themselves)
  // options: "None" | "User" | "Friend" | "Outgoing" | "Incoming" | "Blocked" | "BlockedOther";
  string relationship = 4;
  optional string display_name = 5; // 64 char
  optional int32 badges = 6;
  optional string status_text = 7; // 510 char
  optional UserStatus status_presence = 8; // 32 char
  optional string profile_content = 9; // text
  // ulid (26 chars) Reference to files collection
  optional string profile_background_id = 10;
  bool privileged = 11;
  optional int64 suspended_until = 12;
  int64 created_at = 13; // unix timestamp miliseconds
  int64 updated_at = 14; // unix timestamp miliseconds
  bool verified = 15;
  optional shared.v1.File avatar = 16;
  repeated service.v1.UserRelationship relations = 17;
  optional service.v1.Bot bot = 18;
  optional bool online = 19;
}

enum UserFlag {
  USER_FLAG_UNSPECIFIED = 0;
  USER_FLAG_SUSPENDED_UNTIL = 1;
  USER_FLAG_DELETED = 2;
  USER_FLAG_BANNED = 4;
  USER_FLAG_SPAM = 8;
}

message UsersCreateRequest {
  string email = 1;
  string password = 2;
  string username = 3;
}

message UsersCreateResponse {
  oneof response {
    UsersCreateResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message UsersCreateResponseData {
  string message = 1;
}

message UsersLoginRequest {
  string email = 1;
  string password = 2;
  string mfa = 3;
  string login_challenge = 4;
}

message UsersLoginResponse {
  oneof response {
    UsersLoginResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message UsersLoginResponseData {
  string redirect_to = 1;
}

message UsersEmailConfirmationRequest {
  string token = 1;
}

message UsersEmailConfirmationResponse {
  oneof response {
    UsersEmailConfirmationResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message UsersEmailConfirmationResponseData {
  string message = 1;
}

message UsersForgotPasswordRequest {
  string email = 1;
}

message UsersForgotPasswordResponse {
  oneof response {
    UsersForgotPasswordResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message UsersForgotPasswordResponseData {
  string message = 1;
}

message UsersResetPasswordRequest {
  string token = 1;
  string password = 2;
  string password_confirmation = 3;
}

message UsersResetPasswordResponse {
  oneof response {
    UsersResetPasswordResponseData data = 1;
    shared.v1.AppError error = 2;
  }
}

message UsersResetPasswordResponseData {
  string message = 1;
}
