syntax = "proto3";

package shared.v1;

// ===========================================
// FILE TYPE
// ===========================================
message File {
  // Unique Id
  string id = 1;

  // ID of user who uploaded this file
  string uploader_id = 2;

  // Tag / bucket this file was uploaded to
  string bucket = 3;

  // Original filename
  string filename = 4;

  // Raw content type of this file
  string content_type = 5;

  // Size of this file (in bytes)
  int64 size = 6;

  // Hash of this file
  string hash = 7;

  // When this file was uploaded
  int64 uploaded_at = 8;

  // Whether this file was deleted
  optional bool deleted = 9;

  // Whether this file was reported
  optional bool reported = 10;

  FileMetadata metadata = 11;

  // Whether this file should have a spoiler
  bool is_spoiler = 12;
}

message FileMetadata {
  oneof type {
    FileMetadataFile file = 1;
    FileMetadataText text = 2;
    FileImage image = 3;
    FileVideo video = 4;
    FileAudio audio = 5;
  }
}

message FileMetadataFile {}

message FileMetadataText {}

message FileImage {
  uint32 width = 1;
  uint32 height = 2;
}

message FileVideo {
  uint32 width = 1;
  uint32 height = 2;
}

message FileAudio {}
