// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file shared/v1/error.proto (package shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v1/error.proto.
 */
export const file_shared_v1_error: GenFile = /*@__PURE__*/
  fileDesc("ChVzaGFyZWQvdjEvZXJyb3IucHJvdG8SCXNoYXJlZC52MSL6AQoIQXBwRXJyb3ISCgoCaWQYASABKAkSDwoHbWVzc2FnZRgCIAEoCRIWCg5kZXRhaWxlZF9lcnJvchgDIAEoCRITCgtzdGF0dXNfY29kZRgFIAEoDRIQCghsb2NhdGlvbhgGIAEoCRIdChBza2lwX3RyYW5zbGF0aW9uGAcgASgISACIAQESLwoGZXJyb3JzGAggAygLMh8uc2hhcmVkLnYxLkFwcEVycm9yLkVycm9yc0VudHJ5Gi0KC0Vycm9yc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCEwoRX3NraXBfdHJhbnNsYXRpb25iBnByb3RvMw");

/**
 * @generated from message shared.v1.AppError
 */
export type AppError = Message<"shared.v1.AppError"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * displayed to the end user without debugging info
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Internal debug info
   *
   * @generated from field: string detailed_error = 3;
   */
  detailedError: string;

  /**
   * grpc status code
   *
   * @generated from field: uint32 status_code = 5;
   */
  statusCode: number;

  /**
   * Code path or func name
   *
   * @generated from field: string location = 6;
   */
  location: string;

  /**
   * If false, i18n may not apply
   *
   * @generated from field: optional bool skip_translation = 7;
   */
  skipTranslation?: boolean;

  /**
   * @generated from field: map<string, string> errors = 8;
   */
  errors: { [key: string]: string };
};

/**
 * Describes the message shared.v1.AppError.
 * Use `create(AppErrorSchema)` to create a new message.
 */
export const AppErrorSchema: GenMessage<AppError> = /*@__PURE__*/
  messageDesc(file_shared_v1_error, 0);

