// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file shared/v1/files.proto (package shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v1/files.proto.
 */
export const file_shared_v1_files: GenFile = /*@__PURE__*/
  fileDesc("ChVzaGFyZWQvdjEvZmlsZXMucHJvdG8SCXNoYXJlZC52MSLWAQoERmlsZRIKCgJpZBgBIAEoCRITCgt1cGxvYWRlcl9pZBgCIAEoCRIOCgZidWNrZXQYAyABKAkSEAoIZmlsZW5hbWUYBCABKAkSFAoMY29udGVudF90eXBlGAUgASgJEgwKBHNpemUYBiABKAMSDAoEaGFzaBgHIAEoCRITCgt1cGxvYWRlZF9hdBgIIAEoAxIUCgdkZWxldGVkGAkgASgISACIAQESFQoIcmVwb3J0ZWQYCiABKAhIAYgBAUIKCghfZGVsZXRlZEILCglfcmVwb3J0ZWQi5QEKDEZpbGVNZXRhZGF0YRIrCgRmaWxlGAEgASgLMhsuc2hhcmVkLnYxLkZpbGVNZXRhZGF0YUZpbGVIABIrCgR0ZXh0GAIgASgLMhsuc2hhcmVkLnYxLkZpbGVNZXRhZGF0YVRleHRIABIlCgVpbWFnZRgDIAEoCzIULnNoYXJlZC52MS5GaWxlSW1hZ2VIABIlCgV2aWRlbxgEIAEoCzIULnNoYXJlZC52MS5GaWxlVmlkZW9IABIlCgVhdWRpbxgFIAEoCzIULnNoYXJlZC52MS5GaWxlQXVkaW9IAEIGCgR0eXBlIhIKEEZpbGVNZXRhZGF0YUZpbGUiEgoQRmlsZU1ldGFkYXRhVGV4dCIqCglGaWxlSW1hZ2USDQoFd2lkdGgYASABKA0SDgoGaGVpZ2h0GAIgASgNIioKCUZpbGVWaWRlbxINCgV3aWR0aBgBIAEoDRIOCgZoZWlnaHQYAiABKA0iCwoJRmlsZUF1ZGlvYgZwcm90bzM");

/**
 * ===========================================
 * FILE TYPE
 * ===========================================
 *
 * @generated from message shared.v1.File
 */
export type File = Message<"shared.v1.File"> & {
  /**
   * Unique Id
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * ID of user who uploaded this file
   *
   * @generated from field: string uploader_id = 2;
   */
  uploaderId: string;

  /**
   * Tag / bucket this file was uploaded to
   *
   * @generated from field: string bucket = 3;
   */
  bucket: string;

  /**
   * Original filename
   *
   * @generated from field: string filename = 4;
   */
  filename: string;

  /**
   * Raw content type of this file
   *
   * @generated from field: string content_type = 5;
   */
  contentType: string;

  /**
   * Size of this file (in bytes)
   *
   * @generated from field: int64 size = 6;
   */
  size: bigint;

  /**
   * Hash of this file
   *
   * @generated from field: string hash = 7;
   */
  hash: string;

  /**
   * When this file was uploaded
   *
   * @generated from field: int64 uploaded_at = 8;
   */
  uploadedAt: bigint;

  /**
   * Whether this file was deleted
   *
   * @generated from field: optional bool deleted = 9;
   */
  deleted?: boolean;

  /**
   * Whether this file was reported
   *
   * @generated from field: optional bool reported = 10;
   */
  reported?: boolean;
};

/**
 * Describes the message shared.v1.File.
 * Use `create(FileSchema)` to create a new message.
 */
export const FileSchema: GenMessage<File> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 0);

/**
 * @generated from message shared.v1.FileMetadata
 */
export type FileMetadata = Message<"shared.v1.FileMetadata"> & {
  /**
   * @generated from oneof shared.v1.FileMetadata.type
   */
  type: {
    /**
     * @generated from field: shared.v1.FileMetadataFile file = 1;
     */
    value: FileMetadataFile;
    case: "file";
  } | {
    /**
     * @generated from field: shared.v1.FileMetadataText text = 2;
     */
    value: FileMetadataText;
    case: "text";
  } | {
    /**
     * @generated from field: shared.v1.FileImage image = 3;
     */
    value: FileImage;
    case: "image";
  } | {
    /**
     * @generated from field: shared.v1.FileVideo video = 4;
     */
    value: FileVideo;
    case: "video";
  } | {
    /**
     * @generated from field: shared.v1.FileAudio audio = 5;
     */
    value: FileAudio;
    case: "audio";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message shared.v1.FileMetadata.
 * Use `create(FileMetadataSchema)` to create a new message.
 */
export const FileMetadataSchema: GenMessage<FileMetadata> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 1);

/**
 * @generated from message shared.v1.FileMetadataFile
 */
export type FileMetadataFile = Message<"shared.v1.FileMetadataFile"> & {
};

/**
 * Describes the message shared.v1.FileMetadataFile.
 * Use `create(FileMetadataFileSchema)` to create a new message.
 */
export const FileMetadataFileSchema: GenMessage<FileMetadataFile> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 2);

/**
 * @generated from message shared.v1.FileMetadataText
 */
export type FileMetadataText = Message<"shared.v1.FileMetadataText"> & {
};

/**
 * Describes the message shared.v1.FileMetadataText.
 * Use `create(FileMetadataTextSchema)` to create a new message.
 */
export const FileMetadataTextSchema: GenMessage<FileMetadataText> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 3);

/**
 * @generated from message shared.v1.FileImage
 */
export type FileImage = Message<"shared.v1.FileImage"> & {
  /**
   * @generated from field: uint32 width = 1;
   */
  width: number;

  /**
   * @generated from field: uint32 height = 2;
   */
  height: number;
};

/**
 * Describes the message shared.v1.FileImage.
 * Use `create(FileImageSchema)` to create a new message.
 */
export const FileImageSchema: GenMessage<FileImage> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 4);

/**
 * @generated from message shared.v1.FileVideo
 */
export type FileVideo = Message<"shared.v1.FileVideo"> & {
  /**
   * @generated from field: uint32 width = 1;
   */
  width: number;

  /**
   * @generated from field: uint32 height = 2;
   */
  height: number;
};

/**
 * Describes the message shared.v1.FileVideo.
 * Use `create(FileVideoSchema)` to create a new message.
 */
export const FileVideoSchema: GenMessage<FileVideo> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 5);

/**
 * @generated from message shared.v1.FileAudio
 */
export type FileAudio = Message<"shared.v1.FileAudio"> & {
};

/**
 * Describes the message shared.v1.FileAudio.
 * Use `create(FileAudioSchema)` to create a new message.
 */
export const FileAudioSchema: GenMessage<FileAudio> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 6);

