// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file shared/v1/files.proto (package shared.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "./time_pb.js";
import { file_shared_v1_time } from "./time_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shared/v1/files.proto.
 */
export const file_shared_v1_files: GenFile = /*@__PURE__*/
  fileDesc("ChVzaGFyZWQvdjEvZmlsZXMucHJvdG8SCXNoYXJlZC52MSLsAQoERmlsZRIKCgJpZBgBIAEoCRITCgt1cGxvYWRlcl9pZBgCIAEoCRIOCgZidWNrZXQYAyABKAkSEAoIZmlsZW5hbWUYBCABKAkSFAoMY29udGVudF90eXBlGAUgASgJEgwKBHNpemUYBiABKAMSDAoEaGFzaBgHIAEoCRIpCgt1cGxvYWRlZF9hdBgIIAEoCzIULnNoYXJlZC52MS5UaW1lc3RhbXASFAoHZGVsZXRlZBgJIAEoCEgAiAEBEhUKCHJlcG9ydGVkGAogASgISAGIAQFCCgoIX2RlbGV0ZWRCCwoJX3JlcG9ydGVkYgZwcm90bzM", [file_shared_v1_time]);

/**
 * ===========================================
 * FILE TYPE
 * ===========================================
 *
 * @generated from message shared.v1.File
 */
export type File = Message<"shared.v1.File"> & {
  /**
   * Unique Id
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * ID of user who uploaded this file
   *
   * @generated from field: string uploader_id = 2;
   */
  uploaderId: string;

  /**
   * Tag / bucket this file was uploaded to
   *
   * @generated from field: string bucket = 3;
   */
  bucket: string;

  /**
   * Original filename
   *
   * @generated from field: string filename = 4;
   */
  filename: string;

  /**
   * Raw content type of this file
   *
   * @generated from field: string content_type = 5;
   */
  contentType: string;

  /**
   * Size of this file (in bytes)
   *
   * @generated from field: int64 size = 6;
   */
  size: bigint;

  /**
   * Hash of this file
   *
   * @generated from field: string hash = 7;
   */
  hash: string;

  /**
   * When this file was uploaded
   *
   * @generated from field: shared.v1.Timestamp uploaded_at = 8;
   */
  uploadedAt?: Timestamp;

  /**
   * Whether this file was deleted
   *
   * @generated from field: optional bool deleted = 9;
   */
  deleted?: boolean;

  /**
   * Whether this file was reported
   *
   * @generated from field: optional bool reported = 10;
   */
  reported?: boolean;
};

/**
 * Describes the message shared.v1.File.
 * Use `create(FileSchema)` to create a new message.
 */
export const FileSchema: GenMessage<File> = /*@__PURE__*/
  messageDesc(file_shared_v1_files, 0);

