// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/emoji.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "service.v1";

export interface Emoji {
  /** / Unique Id */
  id: string;
  /** / What owns this emoji */
  parent?:
    | EmojiParent
    | undefined;
  /** / Uploader user id */
  creatorId: string;
  /** / Emoji name */
  name: string;
  /** / Whether the emoji is animated */
  animated: boolean;
  /** / Whether the emoji is marked as nsfw */
  nsfw: boolean;
}

/** / Parent Id of the emoji */
export interface EmojiParent {
  server?: EmojiParentServer | undefined;
  detached?: EmojiParentDetached | undefined;
}

export interface EmojiParentServer {
  id: string;
}

/** No fields */
export interface EmojiParentDetached {
}

function createBaseEmoji(): Emoji {
  return { id: "", parent: undefined, creatorId: "", name: "", animated: false, nsfw: false };
}

export const Emoji: MessageFns<Emoji> = {
  encode(message: Emoji, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.parent !== undefined) {
      EmojiParent.encode(message.parent, writer.uint32(18).fork()).join();
    }
    if (message.creatorId !== "") {
      writer.uint32(26).string(message.creatorId);
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.animated !== false) {
      writer.uint32(40).bool(message.animated);
    }
    if (message.nsfw !== false) {
      writer.uint32(48).bool(message.nsfw);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Emoji {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmoji();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.parent = EmojiParent.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.creatorId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.animated = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.nsfw = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Emoji {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      parent: isSet(object.parent) ? EmojiParent.fromJSON(object.parent) : undefined,
      creatorId: isSet(object.creatorId) ? globalThis.String(object.creatorId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      animated: isSet(object.animated) ? globalThis.Boolean(object.animated) : false,
      nsfw: isSet(object.nsfw) ? globalThis.Boolean(object.nsfw) : false,
    };
  },

  toJSON(message: Emoji): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.parent !== undefined) {
      obj.parent = EmojiParent.toJSON(message.parent);
    }
    if (message.creatorId !== "") {
      obj.creatorId = message.creatorId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.animated !== false) {
      obj.animated = message.animated;
    }
    if (message.nsfw !== false) {
      obj.nsfw = message.nsfw;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Emoji>, I>>(base?: I): Emoji {
    return Emoji.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Emoji>, I>>(object: I): Emoji {
    const message = createBaseEmoji();
    message.id = object.id ?? "";
    message.parent = (object.parent !== undefined && object.parent !== null)
      ? EmojiParent.fromPartial(object.parent)
      : undefined;
    message.creatorId = object.creatorId ?? "";
    message.name = object.name ?? "";
    message.animated = object.animated ?? false;
    message.nsfw = object.nsfw ?? false;
    return message;
  },
};

function createBaseEmojiParent(): EmojiParent {
  return { server: undefined, detached: undefined };
}

export const EmojiParent: MessageFns<EmojiParent> = {
  encode(message: EmojiParent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.server !== undefined) {
      EmojiParentServer.encode(message.server, writer.uint32(10).fork()).join();
    }
    if (message.detached !== undefined) {
      EmojiParentDetached.encode(message.detached, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmojiParent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmojiParent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.server = EmojiParentServer.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.detached = EmojiParentDetached.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmojiParent {
    return {
      server: isSet(object.server) ? EmojiParentServer.fromJSON(object.server) : undefined,
      detached: isSet(object.detached) ? EmojiParentDetached.fromJSON(object.detached) : undefined,
    };
  },

  toJSON(message: EmojiParent): unknown {
    const obj: any = {};
    if (message.server !== undefined) {
      obj.server = EmojiParentServer.toJSON(message.server);
    }
    if (message.detached !== undefined) {
      obj.detached = EmojiParentDetached.toJSON(message.detached);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmojiParent>, I>>(base?: I): EmojiParent {
    return EmojiParent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmojiParent>, I>>(object: I): EmojiParent {
    const message = createBaseEmojiParent();
    message.server = (object.server !== undefined && object.server !== null)
      ? EmojiParentServer.fromPartial(object.server)
      : undefined;
    message.detached = (object.detached !== undefined && object.detached !== null)
      ? EmojiParentDetached.fromPartial(object.detached)
      : undefined;
    return message;
  },
};

function createBaseEmojiParentServer(): EmojiParentServer {
  return { id: "" };
}

export const EmojiParentServer: MessageFns<EmojiParentServer> = {
  encode(message: EmojiParentServer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmojiParentServer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmojiParentServer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EmojiParentServer {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: EmojiParentServer): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EmojiParentServer>, I>>(base?: I): EmojiParentServer {
    return EmojiParentServer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmojiParentServer>, I>>(object: I): EmojiParentServer {
    const message = createBaseEmojiParentServer();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseEmojiParentDetached(): EmojiParentDetached {
  return {};
}

export const EmojiParentDetached: MessageFns<EmojiParentDetached> = {
  encode(_: EmojiParentDetached, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmojiParentDetached {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmojiParentDetached();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): EmojiParentDetached {
    return {};
  },

  toJSON(_: EmojiParentDetached): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmojiParentDetached>, I>>(base?: I): EmojiParentDetached {
    return EmojiParentDetached.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmojiParentDetached>, I>>(_: I): EmojiParentDetached {
    const message = createBaseEmojiParentDetached();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
