// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               unknown
// source: service/v1/main.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { ChannelsGetRequest, ChannelsGetResponse } from "./channels";
import { GroupsCreateRequest, GroupsCreateResponse, GroupsListRequest, GroupsListResponse } from "./groups";
import { MessagesGetRequest, MessagesGetResponse, MessagesSearchRequest, MessagesSearchResponse } from "./messages";
import { SearchUsernamesRequest, SearchUsernamesResponse } from "./search";
import {
  UsersCreateRequest,
  UsersCreateResponse,
  UsersEmailConfirmationRequest,
  UsersEmailConfirmationResponse,
  UsersForgotPasswordRequest,
  UsersForgotPasswordResponse,
  UsersLoginRequest,
  UsersLoginResponse,
  UsersResetPasswordRequest,
  UsersResetPasswordResponse,
} from "./users";

export const protobufPackage = "service.v1";

export interface ChatyService {
  UsersCreate(request: UsersCreateRequest): Promise<UsersCreateResponse>;
  UsersLogin(request: UsersLoginRequest): Promise<UsersLoginResponse>;
  UsersEmailConfirmation(request: UsersEmailConfirmationRequest): Promise<UsersEmailConfirmationResponse>;
  UsersForgotPassword(request: UsersForgotPasswordRequest): Promise<UsersForgotPasswordResponse>;
  UsersResetPassword(request: UsersResetPasswordRequest): Promise<UsersResetPasswordResponse>;
  ChannelsGet(request: ChannelsGetRequest): Promise<ChannelsGetResponse>;
  GroupsCreate(request: GroupsCreateRequest): Promise<GroupsCreateResponse>;
  GroupsList(request: GroupsListRequest): Promise<GroupsListResponse>;
  SearchUsernames(request: SearchUsernamesRequest): Promise<SearchUsernamesResponse>;
  MessagesGet(request: MessagesGetRequest): Promise<MessagesGetResponse>;
  MessagesSearch(request: MessagesSearchRequest): Promise<MessagesSearchResponse>;
}

export const ChatyServiceServiceName = "service.v1.ChatyService";
export class ChatyServiceClientImpl implements ChatyService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ChatyServiceServiceName;
    this.rpc = rpc;
    this.UsersCreate = this.UsersCreate.bind(this);
    this.UsersLogin = this.UsersLogin.bind(this);
    this.UsersEmailConfirmation = this.UsersEmailConfirmation.bind(this);
    this.UsersForgotPassword = this.UsersForgotPassword.bind(this);
    this.UsersResetPassword = this.UsersResetPassword.bind(this);
    this.ChannelsGet = this.ChannelsGet.bind(this);
    this.GroupsCreate = this.GroupsCreate.bind(this);
    this.GroupsList = this.GroupsList.bind(this);
    this.SearchUsernames = this.SearchUsernames.bind(this);
    this.MessagesGet = this.MessagesGet.bind(this);
    this.MessagesSearch = this.MessagesSearch.bind(this);
  }
  UsersCreate(request: UsersCreateRequest): Promise<UsersCreateResponse> {
    const data = UsersCreateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UsersCreate", data);
    return promise.then((data) => UsersCreateResponse.decode(new BinaryReader(data)));
  }

  UsersLogin(request: UsersLoginRequest): Promise<UsersLoginResponse> {
    const data = UsersLoginRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UsersLogin", data);
    return promise.then((data) => UsersLoginResponse.decode(new BinaryReader(data)));
  }

  UsersEmailConfirmation(request: UsersEmailConfirmationRequest): Promise<UsersEmailConfirmationResponse> {
    const data = UsersEmailConfirmationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UsersEmailConfirmation", data);
    return promise.then((data) => UsersEmailConfirmationResponse.decode(new BinaryReader(data)));
  }

  UsersForgotPassword(request: UsersForgotPasswordRequest): Promise<UsersForgotPasswordResponse> {
    const data = UsersForgotPasswordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UsersForgotPassword", data);
    return promise.then((data) => UsersForgotPasswordResponse.decode(new BinaryReader(data)));
  }

  UsersResetPassword(request: UsersResetPasswordRequest): Promise<UsersResetPasswordResponse> {
    const data = UsersResetPasswordRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UsersResetPassword", data);
    return promise.then((data) => UsersResetPasswordResponse.decode(new BinaryReader(data)));
  }

  ChannelsGet(request: ChannelsGetRequest): Promise<ChannelsGetResponse> {
    const data = ChannelsGetRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ChannelsGet", data);
    return promise.then((data) => ChannelsGetResponse.decode(new BinaryReader(data)));
  }

  GroupsCreate(request: GroupsCreateRequest): Promise<GroupsCreateResponse> {
    const data = GroupsCreateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GroupsCreate", data);
    return promise.then((data) => GroupsCreateResponse.decode(new BinaryReader(data)));
  }

  GroupsList(request: GroupsListRequest): Promise<GroupsListResponse> {
    const data = GroupsListRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GroupsList", data);
    return promise.then((data) => GroupsListResponse.decode(new BinaryReader(data)));
  }

  SearchUsernames(request: SearchUsernamesRequest): Promise<SearchUsernamesResponse> {
    const data = SearchUsernamesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SearchUsernames", data);
    return promise.then((data) => SearchUsernamesResponse.decode(new BinaryReader(data)));
  }

  MessagesGet(request: MessagesGetRequest): Promise<MessagesGetResponse> {
    const data = MessagesGetRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MessagesGet", data);
    return promise.then((data) => MessagesGetResponse.decode(new BinaryReader(data)));
  }

  MessagesSearch(request: MessagesSearchRequest): Promise<MessagesSearchResponse> {
    const data = MessagesSearchRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MessagesSearch", data);
    return promise.then((data) => MessagesSearchResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
